### ISSUE TITLE
What about an unified header file?

### ISSUE THREAD

**Issue by enzo-simone** [nu-book/zxing-cpp#102]
IMHO it should be a nicer user experience to have a single `ZXing.h` file that needs to be included to use the whole library.
If you see the `scan_image.cpp` example there are 8 files that needs to be included to compile the code, a fairly amount.
Or maybe we can agree on having two files `BarcodeReader.h` and `BarcodeGenerator.h`

Thank you.

**Comment by axxel** [comment]
I believe more than just a header that includes the 8 single ones required right now, it would be helpful to add a simple API along the lines of what you described in #104. Which is pretty much what the python wrapper is doing, too.

I went ahead and implemented something as a base for discussion: https://github.com/nu-book/zxing-cpp/commit/aa47b22581738b64023c8b7bedcc0c6b8b44a9e8.

What I still find debatable is the fact that Result::text() returns a std::wstring. Which is rather unusual / feels windows specific? Maybe we could templetize the Readers and the `Result` on `char` vs. `wchar` and have the Utf8 conversion been done automatically when char is requested? Maybe not worth the work, just a thought... @huycn?

**Comment by huycn** [comment]
IMHO, it isn't worth the work. By returning std::wstring, it's clearly it's a text in Unicode. If that was std::string, you would not be sure, it may be UTF-8, binary, or just whatever codec, so returning std::string would be less than ideal. A templated version will indeed avoid such confusion, but I don't think it's worth the cost to render interface more complex.

By the way, your new API added in https://github.com/nu-book/zxing-cpp/commit/aa47b22581738b64023c8b7bedcc0c6b8b44a9e8 is a good idea. I was hesitating a bit to add a header that it's not used anywhere, but I agree with @enzo-simone it is not too obvious to includes many things for a simple usecase. Your solution is far better.

**Comment by axxel** [comment]
Glad you liked the `ReadBarcode` proposal. Now if the OP is happy with it as well, I'll update the README accordingly. ;).

Thanks for your input on string vs wstring subject. I agree with you. I believe another approach would be a little conversion struct for `Result`, maybe `StringResult<StrT>` that contains the basic information as string/wstring (error, text, format, position, maybe some metadata) - similar to your [`ReadResult`](https://github.com/nu-book/zxing-cpp/blob/538d214570edeba29763678cdf9fc9415da8b6ce/wrappers/wasm/BarcodeReader.cpp#L37).

It seems every interface (wasm/python/example/blackbox-tests) does that Result -> string stuff anyway. I could even see a point in having `ReadBardcode` then directly returning that as it would be really the most simple interface (not the most performant).

**Comment by huycn** [comment]
Yes, as long as it remains simple and clear, I agree such automatic can be handy.

**Comment by enzo-simone** [comment]
@axxel thank you very much for the new API which makes immediate for any basic user to access decoding functionality just off-the-shelf.

But, yes call me finicky, this is one of the solution. Advanced users would need to access all the classes and utilities implemented in the library (e.g. to fine tune performances), and currently they still have to manually include a certain number of headers. I'm sorry not have presented my point more explicitly in my first rant, but I'm talking about something like the one-liner
`#include <opencv2/opencv.hpp>`
in the OpenCV library which gives you just all-the-stuff™.

While trying to create a wrapping header file I still stumble across .h files which includes other headers using the quotes syntax, but included headers do not lie at same level in the filesystem, so I get compilation errors (I'm an Visual C++ guy if this matters).

**Comment by axxel** [comment]
@enzo-simone I see your point but I have two observations to make:

1) The main issue why we need 8 instead of maybe 2 includes is, because @huycn chose to use forward declared classes where possible. I assume, the goal was to bring compilation time to a minimum. Interestingly I just saw a talk from Titus Winters from CPPCON 2019 where he claimed that this virtually never actually helps observable with compilation times.

2) This header would not help with stuff that you can currently not include because of the quote syntax. In that case there is either another 'bug' with the relative include paths or the header you try to include should be considered 'internal'. Which one is it and what are you trying to do with it?

**Comment by enzo-simone** [comment]
1. OK, let's stick to current design
2. my bad, I overlooked that commit b0ced71fdfef14527fd2a073acea08253d468c12 fixed the include problems

Thank you.

**Comment by axxel** [comment]
Now that @dabrain34 contributed some documentation for my single function ReadBarcode proposal, I'd like to point out that this interface should not be considered stable, yet. I'd like to bring in my suggested string based result struct (see above) and probably also abstract the memory-layout parameters into a simple struct so that there is only one ReadBarcode function. With the goal of making this API as clean/simple/user-friendly as possible.

Maybe my ideas will not find consensus but I'd like to discuss them before setting the current code 'in stone'. I just did not have the time recently and will likely not for a few more weeks (those pesky day jobs... ;)
