### ISSUE TITLE
Multiple QR codes decode

### ISSUE THREAD

**Issue by rezodlub** [nu-book/zxing-cpp#105]
Are there any plans on adding Multi code decoder, something like QRCodeMultiReader in the official ZXIng?

**Comment by axxel** [comment]
I had a quick look at what they do and I believe if that feature is of importance, then one would implement it differently to support more use-cases. What would be your use-case? Can you provide a 'difficult' (think e.g. rotation) real-world sample of a multi code image?

**Comment by rezodlub** [comment]
My use case is actually a QR based backup, which has to be split into multiple QR codes, as there's way more data to be stored than I can fit into a single code. So in the end it's actually a 3*4 grid of QR codes on an A4 piece of paper. It might not make good sample data, as it's really nicely geometrically aligned, while some other use cases would most probably not be. Of course, I can provide you with sample data.

**Comment by axxel** [comment]
So you control both the generation and the scanning side of the problem? If so, maybe you could simply use a different type of code like DataMatrix. I believe it can store more data in one code than QR but not necessarily enough for your application. Aztec might also be worth a look but I know next to nothing about that.

If you want to stick with QR, then a sample would certainly help in estimating the best approach.

**Comment by rezodlub** [comment]
Sorry for taking so long before sending sample images. 

![1-page-001](https://user-images.githubusercontent.com/6959557/66841084-6f55a880-ef69-11e9-96e2-baffd4d844ab.jpg)
![1-page-002](https://user-images.githubusercontent.com/6959557/66841085-6f55a880-ef69-11e9-8084-0ec128ea68cc.jpg)
![1-page-003](https://user-images.githubusercontent.com/6959557/66841087-6fee3f00-ef69-11e9-8daa-88eabb0427bb.jpg)

**Comment by axxel** [comment]
Seems like an unusual application you have there. There is one thing that I immediately noticed: There seems to be something off with the generation of your code or rather the 'rendering' of the data. It seems the codes have a width of say 30 modules and they get rendered to an image part with something like 35 pixels which results in e.g. the finder patterns being asymmetrical with most likely invalid black-to-white ratios. The spec says 1:1:3:1:1 but I see something more like e.g. 2:1:6:2:1 in lower left pattern of the last QR-code.

Since it is an artificially generated image, you should be able to start with a 'perfect' sample. Before going any further, I'd first look into that.

**Comment by rezodlub** [comment]
What I attached was actually a print to pdf, converted back to an image at 150 dpi. That's much closer to the real-world imperfection of cameras that scan the image. In real application restoration process is done by scanning the image(s) with a camera from a paper. And if more a visible at a time, they should all be scanned. Another library (ZBar) does pretty good job of detection/decoding, but sometimes needs to rescan the same image multiple times, to detect all QR codes. That's why I'd actually like to do parallel detection/decoding with two libraries to get a better detection rate.

**Comment by axxel** [comment]
> What I attached was actually a print to pdf, converted back to an image at 150 dpi.

That explains my observation very well.

> That's much closer to the real-world imperfection of cameras that scan the image.

Most definitively not. If you want to test if your real-world scans/photographs work, use one of those.

**Comment by bimusiek** [comment]
Hey, we have different use case. 

Our app scans screenshots of PDFs users take, and on those PDFs there is one main QR code we need to get and sometimes there is QR code from some advertisement. Unfortunatelly, the lib finds only advertisement qr code instead of main one we need. 

Would it work to get points of the image, remove the qr code from the image and scan it again?

**Comment by axxel** [comment]
@bimusiek That should certainly work. Have a look at the `ZXing::Result::resultPoints()` function. If you used that to set the respective area to either black or white and rescan the image you should get the other code.

**Comment by bimusiek** [comment]
I did end up using resultPoints to paint a rectangle, however for barcodes pdf417 I am getting totally crazy points. I will try to prepare some example soon.

**Comment by axxel** [comment]
That PDF417 does not work as nice is no surprise to me. I had a closer look at the code last year (in a cleanup attempt that I could not finish before I had to move back to other stuff) and it is rather 'convoluted', compared to the QR reader stuff. If you want to supply examples, please open a new issue as that would not have anything to do with this topic here. Thanks.
