### ISSUE TITLE
Using wchar argument on function accepting char type

### ISSUE THREAD

**Issue by enzo-simone** [nu-book/zxing-cpp#107]
Here we use `wchar` arguments for `std::toupper` function.
https://github.com/nu-book/zxing-cpp/blob/46a4b60337adaecc90d1b85bfe47b49c6bb1f1ca/core/src/oned/ODCodabarWriter.cpp#L59-L64

Is worth considering changing (overloading?) `Contains` to accept `wchar`s?

**Comment by axxel** [comment]
I would suggest to add a check that goes through all `contents` characters and tests if any of those is `> 255` and if so, throw an exception (like below).

**Comment by axxel** [comment]
Interesting: after my added thought from above, I just hacked those 3 lines to see how it looks and realized that it does not help to prevent this potential problem (detecting the character `L"A" + 256` as invalid) because calling `std::toupper()` with anything above 255 that is not `EOF` is undefined behaviour. So one would need to bounds-check x before calling `toupper`, hence, nothing gained by doing anything to `Contains` which comes afterwards. Then I started wondering: why have that `toupper` in the first place? According to the "specification" of Codabar (wikipedia), the start/end characters are referred to as "ABCD", not "abcd", so why bother accepting a mix of both? They are also not tested for in the unit tests. My recommendation: remove `toupper` and add unit tests to check for invalid characters (I have the changes lying around here, ready to commit). @huycn any thoughts on this?

**Comment by enzo-simone** [comment]
What about changing
```
static const std::wstring START_END_CHARS =  L"ABCD";
static const std::wstring ALT_START_END_CHARS = L"TN*E";
static const std::wstring CHARS_WHICH_ARE_TEN_LENGTH_EACH_AFTER_DECODED = L"/:+.";
```
and then
```
wchar_t firstChar = std::towupper(contents[0]);
wchar_t lastChar = std::towupper(contents[contents.length() - 1]);
```

**Comment by axxel** [comment]
`towupper` - how obvious, now that you said it ;). I'd still argue that it is unhelpful to have it there in the first place but without some feedback from @huycn, I'll push my fix including the towupper to have it behave the same as before.

**Comment by axxel** [comment]
> so now we can use the container version of Contains

note: that version works just fine with a wchar_t[] (thanks to `std::begin()` and friends), no heap allocation required.

**Comment by enzo-simone** [comment]
Yes, thanks. So we need to wait for @huycn before closing this issue?

**Comment by axxel** [comment]
No, I consider this issue fixed. If he agrees with me about toupper, I'll simply remove the two lines later.

**Comment by huycn** [comment]
I'm late to the party, but yes, I agree we can just reject the non-standard lowercase letters even though the [original code](https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/oned/CodaBarWriter.java#L49-L50) accepts it.
