### ISSUE TITLE
Cannot decode seemingly perfect barcode

### ISSUE THREAD

**Issue by Nonononoki** [nu-book/zxing-cpp#136]
![barcode_zxing](https://user-images.githubusercontent.com/11612388/85562575-e67d2980-b62c-11ea-868b-6030f91dcbcb.png)

Other online barcode decoders are able to decode it correctly (e.g. https://online-barcode-reader.inliteresearch.com/ and https://www.onlinebarcodereader.com/).

I tried to make the code taller, but no luck using Zxing:
![barcode_zxing_tall](https://user-images.githubusercontent.com/11612388/85564673-c0588900-b62e-11ea-870c-0165f400d35b.png)

**Comment by axxel** [comment]
I had a close look at your sample and the source code and it turns out, your barcode is far from perfect. I generated a perfect sample of the same text and put it right next to yours (top is your input, bottom is generated).

![code128-fail-merge](https://user-images.githubusercontent.com/1038346/85590438-b3469480-b644-11ea-9dce-6ac9ee206afd.png)

As you can see, they differ quite a bit left of the center. I have no idea how the other decoders work but I see why zxing has to fail: The problematic part has a pattern of: (The numbers are reversed as your input is upside-down.)
```
15, 13, 13, 34, 19, 11  <- input
2,  1,  2,  3,  2,  1   <- best match by zxing (code 31)
1,  2,  1,  4,  2,  1   <- 'correct' match (code 66)
```
You can see your white (the left-most '13') should be twice as wide as the two surrounding blacks ('15' and '13). And the '34' is also too small compared to the '11'.

I'm open to suggestions on how to improve the matching.
