### ISSUE TITLE
Multi-barcode-detection: interface discussion

### ISSUE THREAD

**Issue by axxel** [nu-book/zxing-cpp#138]
While working on my 'long term' project of redesigning the 1D readers, I noticed that after what I pan to change, it would be pretty easy to report back all (distinct) 1D codes instead of only one. Basically, just 'keep on looking' instead of breaking after the first.

For the 2D codes this can also be achieved relatively easy: After one is found, mask out the data from the BitMatrix where the code was detected and simply look again.

I'll only concentrate on the new `ReadBarcode` interface (also in the hope that every client switches over to that, once it is set in stone). There would then be a new `ReadBarcodes` (plural) function that returns a list of detected codes. The `DecodeHints` would be extended to allow the specification of a `detectionLimit`, which could be set to 1 to get the old behavior. That would be a lot faster than the unlimited cased if there actually is a code to be found. The default should be 'unlimited', though, in the spirit of my also suggested change of the default values for `tryRotate` and `tryHarder`. We could also keep the `ReadBarcode` function which would simply call the other with the limit set to 1.

Those two issues should then be solved: #105 and #131.

Any feedback appreciated.

**Comment by huycn** [comment]
By 'keep on looking', do you mean, we continue to look on the same row of pixels? Will it work if we have two barcodes vertically arranged?

For 2D codes, I'm not sure how you will mask out the data, but if we still can support concurrent readers on single image buffer, it will be ok for me :)  Note also currently, all readers are stateless as advertised in Readme, thus they are also thread-safe: same reader can be used in multiple concurrent threads (although there is not a lot of benefits to do so), it's preferable to keep the same behavior (at least by default).

**Comment by axxel** [comment]
> By 'keep on looking', do you mean, we continue to look on the same row of pixels? Will it work if we have two barcodes vertically arranged?

There are two limitations right now:
1. Some decoders (e.g. ITF and RSSExpanded) currently don't work at all if two codes of the same type are vertically next to each other. This will need fixing anyway.
2. It will be necessary to restart a scan in the middle of a row.

Then 'keep looking' will mean on the same and on different rows.

> For 2D codes, I'm not sure how you will mask out the data, but if we still can support concurrent readers on single image buffer, it will be ok for me :)

My idea was to modify the BitMatrix, so the original image buffer does not have to be touched. 

> Note also currently, all readers are stateless as advertised in Readme, thus they are also thread-safe: same reader can be used in multiple concurrent threads (although there is not a lot of benefits to do so), it's preferable to keep the same behavior (at least by default).

Making sure we can simultaneously work on the same data from different threads will require ether some locking or copy-on-write behavior. Supporting the case of having two threads executing the same reader on the same data, make no sense to me at all. They would simply do the exact same work twice.

**Comment by huycn** [comment]
Modify the BitMatrix is good idea, as it's temporarily created in one run. By "same data", I mean user-provided input image buffer. The idea is to avoid making copies of image buffer as it could be expensive. I see no problem modifying BitMatrix.

You are right, we don't need to support same reader and same data on different threads. But it can happen that a client uses same reader can run in multiple threads for different images (e.g. when the place where reader is created is far from where it is used). Currently such usage is valid, it's preferable if it can remain so.

**Comment by overriden-sfdd** [comment]
@axxel, are you currently working on this feature? I have a project where I need to utilize multiple 1D barcode detection and I came up with a simple solution, but it's unstable and inefficient. I'm not very familiar with the core of this repository, but I would like to have this feature, and if nobody else is working on it, I would like to contribute. Does that make sense?

**Comment by axxel** [comment]
Nice timing: after months of doing very little on this project, I was just (in this moment) reviewing this old discussion and trying to remember what I had in mind last year to decide on whether or not to start working on this again. Do you have some code to look at somewhere or can you describe your solution?

**Comment by overriden-sfdd** [comment]
The only thing I have is a temporary solution inside of my project. It simply does a while loop until we don't find any valid barcode on the image. Each time we have found a barcode, reconstruct rectangle area based on two output points and "erase" this region from the image. After that, we feedforward the image with the previously detected barcode "erased" and generally **ReadBarcode** should find another barcode if it's present. But of course this is, as I said, an inefficient solution. I don't really have anything else except this thread and 2 issues attached. I was planning to dig deep into the source code to understand what we can do to create a multi barcode detection. Even if I need to do this from the very basics, I will do that because I really need this feature.

**Comment by axxel** [comment]
I see how that is inefficient but what do you mean by "unstable"? Do you have a (few) good and representing example(s) of your real world images that you could share? I will look into this. Someone "really needing" this is a very good excuse to spent a little time on that now :).

**Comment by overriden-sfdd** [comment]
I "erase" the barcode area by simply filling the area with some color. It's very simple and straightforward, but sometimes detectors, because of these random filled-with-color rectangular areas, are unable to find the barcode that is easily read if cropped .
And of course I can share a couple of examples with you.
![example2](https://user-images.githubusercontent.com/47534862/126175512-19e0507d-2417-47ec-994d-81cefc7a7457.jpeg)

![example1](https://user-images.githubusercontent.com/47534862/126175051-ece65674-f040-4fb7-86cd-faced6134332.jpeg)

![example](https://user-images.githubusercontent.com/47534862/126174601-5d8e028b-3ae0-4c87-92ea-3dd2d55889b9.jpeg)

**Comment by overriden-sfdd** [comment]
And if you don't have a time for this feature, I would be happy if you could share your thoughts about how to do it better and which part of the code can be changed/extended to create this feature.

**Comment by axxel** [comment]
@overriden-sfdd I'd be interested to know if this is working for you. I tested your samples and got promising (although not perfect) results: in the first image, 2 of 3 codes are detected (the upper left is non-conformant as it has not enough quite-zone in front) and in the shoo box the central code-128 seems to have an issue as well (not analyzed, yet).

**Comment by overriden-sfdd** [comment]
I just finished testing your new multiple barcode on a 7k image dataset. It's impressive that experimental API works that good. However, it gives worse results (by not a large margin) than my previous dumb approach.
Being more concrete my numbers were around 93% with the simple approach, and now they are around 92%. To help you improve this, I will try to find samples with the poorer quality than before.

And besides, I have a couple of suggestions about the functionality multiple barcode detection can have. I'll write my thoughts in the next comment with the "failed" samples.

Great job, by the way! Thank you.

**Comment by overriden-sfdd** [comment]
**First 3 images were processed by my simple approach.**

![1_better_custom](https://user-images.githubusercontent.com/47534862/126553605-79047765-61ec-428c-bf2f-50aa2a67ab81.jpg)
![2_better_custom](https://user-images.githubusercontent.com/47534862/126553612-2c99e8fb-776a-414c-a2cd-d5235080de45.jpg)
![3_better_custom](https://user-images.githubusercontent.com/47534862/126553617-784195e2-b0c5-49c9-abb6-3bade6fb5f82.jpg)


**Other 3 images were processed by the ZXing library.**

![1_worse_zxing](https://user-images.githubusercontent.com/47534862/126553814-b3a810d3-2be6-4943-9493-dc1a53773ec9.jpg)
![2_worse_zxing](https://user-images.githubusercontent.com/47534862/126553824-313abaa0-b703-4659-a237-ae769183adca.jpg)
![3_worse_zxing](https://user-images.githubusercontent.com/47534862/126553837-1d162c44-5967-4997-86ec-c29cd25a6b24.jpg)

**Comment by axxel** [comment]
Those results are puzzling:
 * I can only get the rightmost code of the first example be detected if I downscale the image. I fail to see how your approach can detect that (based on the same ZXingCpp code, just using the `ReadBarcode` function instead of the new one).
 * I can detect both of the codes in the last image (even with the overlay) without any changes just fine.

This suggest to me that you are using the library differently compared to the `ZXingReader` example program. Could you please confirm my results with your build of `ZXingReader`?

To look into the second example, I'd need the image without the overlay part, because it partly destroys the barcodes.

**Comment by axxel** [comment]
Regarding the second example, there is something else fishy: my new code can't possibly return the same code (format + text) twice from the same image (by construction). There are only 3 different codes visible, so you can not get all 3 copies of the "maritime assault low" shoo but your overlay suggests as much. So I don't need the second example without the overlay, because it works already as expected even with the overlay.

If you'd need to know if there are multiple copies of the same code in the image, that would be impossible for this approach to get 100% right. For this particular example I could see a viable heuristic to achieve that but it won't work in general.

**Comment by overriden-sfdd** [comment]
Ok, I dug deeper and found out that your recent changes are not the reason why some of the barcodes on the first and on the third image weren't found. However, it's still strange and unclear to me why the second image barcode detector can't find the last barcode. I didn't really understand your explanations about why it can't be 100% right in that case. Probably it's because of that I don't know what's going on under the hood and how these barcode patterns are detected.

Taking in account everything that I figured out about the root of the last problem, I want to switch to my suggestion that I mentioned earlier today.
Coming back to API functionality. As a user I would like to have a little bit more advanced possibilities to interface with the multiple barcode detection.

At first glance, I see that multiple barcode detection works just like ReadBarcode for single object detection, but IMO when we have a multiple object detection function we can't keep the same level of abstraction.

For example, we have 3 different barcodes in the image and this image is really hard for detectors. There is a shadow on the **first** barcode, the **second** barcode for some reason is too blurry to recognize, and finally the **third** barcode is absolutely fine. If we have only 1 function, we will be forced to call ReadBarcodes 3 times for each case scenario (I assume that all 3 barcodes require different ways of preprocessing to get detected by ZXing detector).

My proposal is to have something like a ScanArea iterator. With this iterator we will be able to start scanning for a barcode from any row in the image.

And we will have function ScanUntilFound. It takes "ScanArea iterator" from which it starts scanning for a barcode (I don't know how it works under the hood, but I assume it goes row by row bottom-up looking for a pattern). That function scans the image and once barcode is found it stops and returns the iterator on the next row.

Use-case scenario: the last example will be reused here. Since we have an image row-by-row iterator which allows us to scan from any specific part of the image, we can build our algorithm as follows.

1. Take original image, get its ScanArea iterator and feedforward it to the ScanUntilFound function.
2. Scan until iterator is invalid.
3. Once iterator is invalid, change the original image to get rid of possible extreme, specific defects.
4. Feedforward previous iterator (before invalidation, pointing right to the next row after the last found pattern).
5. Repeat step 2-4 until all case-specific preprocessing techniques are over.

**Comment by axxel** [comment]
Before I say something about your "ScanArea iterator" idea, let us please make sure we are on the same page first (which we are not, apparently).
 1. Please confirm that you are able to get all 3 different UPC-A barcodes from the second image (they are 805619539985, 805619551581 and 400004012243) and all 2 of the third image if you simply call `ZXingReader <image.jpg>`.
 2. Please note that the new `ReadBarcodes` function will only report back each text once, regardless how many copies of that barcode are in the image.
 3. Is it important to you to detect that there are 3 boxes (each with it's own barcode) of this one type of shoo in that second image?

**Comment by axxel** [comment]
Note: point 2 and 3 from my last comment have been obsoleted by the latest commit. :)

**Comment by overriden-sfdd** [comment]
I confirm that simply calling ZXingReader <image.jpg> works as expected and returns for the second image 3 barcodes, and for the third image it returns 2 barcodes.

And despite that two last points are already obsolete (thanks for that), I want to say that I should find all the barcodes in the image. It doesn't matter if they have the same value and type, I should find them all.

**Comment by axxel** [comment]
Thanks for the confirmation. That suggests you are using the new function differently/wrong/(not at all?) in your code.

The latest change results in `ZXingReader` finding all 6 symbols in your sample.

**Comment by overriden-sfdd** [comment]
Yes, I assume that the problem was in my fancy preprocessing stage. If your last commit allows Reader to find all 6 symbols in my image, that's just awesome. I will definitely test it today. Very well done, thank you for your hard work.

**Comment by axxel** [comment]
I had a look at why the middle barcode on the shoo-box example does not get detected. Code128 required a 10 module wide quiet zone left and right of the barcode. Here we have barely 5 modules. If you change the `QUIET_ZONE` value in `ODCode128Reader.cpp:186` from 8 to 5, it works. :-/

**Comment by overriden-sfdd** [comment]
Hmmm, very interesting find. Will that ```QUIET_ZONE``` value set to lower number affect the overall performance of the Code128 detector? I mean if we can't change this value directly, there should be a reason for that, right? I will play with this value, thank you.

Talking about your recent changes, 1 hour ago I finished testing it on a 7.5k image dataset and got small boost in localization accuracy. So it seems that your last commit fixed all issues I had, cool. I will take a closer look tomorrow and if something strange pops up, I will let you know.

And coming back to my cumbersome suggestion about the scan area iterator, I would like to say that my idea is very closely related to what ZBar scanner does. I find its image symbol iteration very convenient and flexible.

**Comment by axxel** [comment]
Changing the quiet zone requirement in code128 like this seems to have no significant impact. In general this could lead to a performance degradation and to false positives, both of which it does not with our set of samples. If you find that to be a significant improvement with your test set, I'll consider making that permanent.

If you want to fully control the scanning on a line by line basis, you can call `ReadBarcodes` with individual lines (see `ImageView::cropped()`). I could not quite make sense of your "ScanArea iterator" idea (and have not looked at ZBar, so far) but I want to object your assumption that the current API needs changing to improve it's application in situations like you described here:

> There is a shadow on the first barcode, the second barcode for some reason is too blurry to recognize, and finally the third barcode is absolutely fine.

If there are issues with sharpness or to uneven lighting for ZXing to find it, then that needs to addressed 'under the hood' anyway  and if a solution can be found, it will work with the high level API just fine.

If you find a sample in your set that looks like it should work but does not (with `ZXingReader`), please let me know and I see what can be done about it.

Also note: for high resolution, close up shots, it is beneficial to reduce the resolution before sending it to ZXing.

**Comment by overriden-sfdd** [comment]
I managed to make it there.
### First of all, I took a look at the results of the 7k image dataset, and I found a few cases with worse quality.
**Target types are Code128, EAN-13, UPC-A**. I double checked that my algorithm runs w/o any fancy preprocessing. Attaching images.

1. my = 4, zxing = 1
![IMG_20210510_152748-1620675027711](https://user-images.githubusercontent.com/47534862/126827495-d2b80765-9afb-46e8-af2e-e94fb4e0fa79.jpeg)

2. my = 16, zxing = 8
![image-1619191172645](https://user-images.githubusercontent.com/47534862/126827522-c24f0bbf-c905-4807-ab85-79b628377f03.jpeg)

3. my = 3, zxing = 2
![IMG_20210413_140701-1618340232641](https://user-images.githubusercontent.com/47534862/126827595-cea766e9-d86c-46e1-a2ae-c271b56c990e.jpeg)

I have 2 more samples, but they contain too many barcodes, so it would be hard to debug them. If you want to see my examples with rectangles around barcodes or/and zxing examples with rectangle around barcodes, I can share them with you.

### Second, I ran 500 image subset with 3 different ```QUIET_ZONE``` values and got interesting results.

1.  Standard ```QUIET_ZONE=8``` gives me 1781 alignments.
2.  ```QUIET_ZONE=5``` gives me 1784 alignments.
3.  Standard ```QUIET_ZONE=1``` gives me 1792 alignments.

From these results I can conclude that decreasing ```QUIET_ZONE```value doesn't hurt overall performance. Moreover, in some cases, a smaller value gives a better results.

**Comment by axxel** [comment]
Thanks for those additional samples. I found there to be mainly two issues with the current code that limit the number of detected barcodes:
 1. The line https://github.com/nu-book/zxing-cpp/blob/31caf34b0fbe5443e28b09c22cd5b8ad22567eac/core/src/oned/ODReader.cpp#L92
 limits the number of lines checked per image (here 512, which is already an increase for the multi-barcode case but as I mentioned in the TODO, this not a good approach in general).
 2. The `GlobalHistogramBinarizer` is sensitive to any pixels on the same line. If the barcode is occupying only a fraction of the line, then the threshold (black vs white) can be pretty wrong for the barcode. This issue has always been there but becomes more prominent in the multi-barcode use case, since the individual symbol typically becomes smaller with respect to the total image when compared to the single-barcode use case.

Your approach does not affect issue 1 but might 'accidentally' improve the situation for 2. What color do you use to 'erase' the barcodes that you found?

Question about your 16 vs. 8 result in your second example: Have you checked that those 16 results are actually correct?

**Comment by overriden-sfdd** [comment]
1. The color I use for already detected barcode "erasure" is (100, 100, 100). Values of a brighter or a darker color tend to work worse.
2. Yes, my 16 vs 8 result is wrong only in 1 case, so you can say it's 15 vs 8 result now. I see that its value coverage is 94%.

**Comment by saurabheights** [comment]
@axxel Proposal:-

1. **Add Hint option to disable sorting** - Currently, MultiFormatReader::readMultiple returns multiple duplicate codes for same barcode, due to multiple scan lines passing over barcodes(probably, skimmed the code, haven't done full dive). This can actually produce way too many barcodes depending on barcode size and number of barcodes in the image. Also, I can't think of any good reason to sort them(Q. Are there any application for sorting, would love to know?). IMO, it should be disabled by default, doesn't make ZXing any less accurate, only slower.

2. **Add Hint to remove duplicates** -  The idea is to return a single decoded value for a barcode. Currently, readMultiple generates multiple barcode results for one barcode. To be precise, these are not complete duplicates as they have same data value but different location. 
If location is not important, we can either discard all but one result with duplicate values else just merge all barcode location to a single convex hull.

**Comment by saurabheights** [comment]
Also, this duplicate issue only happens when using ZXing::Binarizer::FixedThreshold.
Gives me 267 barcodes for an image containing a single barcode.

**Comment by axxel** [comment]
Thanks for the input but I can't quite follow your train of though:

 1. The codes are sorted by their position with the idea of getting them presented (close to) the way you'd read them as a human (top-to-bottom and left-to-right). This has no influence what so ever on the number of barcodes you get. Where do you draw than connection from?
 2. The idea I tried to implement is sort of a combination: link several lines close to each other with the same value to one symbol but allow to detect two different symbols with the exact same value at completely different positions (think lots of boxes of the same stuff next to each other).

I currently assume the issues you are having are simply a bug or a limitation of the current implementation but likely not an issue with the interface. Would you please open a new issue for each of your points and provide a sample image each and description of what you expect and what you get? That should help in discussing this further.

**Comment by axxel** [comment]
The interface discussion is finally over with the 1.3 release.
