### ISSUE TITLE
undefined reference to `ZXing::BitMatrix::UNSET_V'

### ISSUE THREAD

**Issue by nicolasfella** [nu-book/zxing-cpp#157]
When building [my project](https://invent.kde.org/pim/kitinerary) against zxing-cpp I get
```
/usr/bin/ld: src/CMakeFiles/KPimItinerary.dir/qimagepurebinarizer.cpp.o: in function `ZXing::BitMatrix::BitMatrix(int, int)':
/home/nico/kde/usr/include/ZXing/BitMatrix.h:82: undefined reference to `ZXing::BitMatrix::UNSET_V'
```
This happens since the switch to C++17 (dfbb3667758d67fcd724faf3ea24ca930513b61b).

The project uses C++14. Switching it to 17 fixes the build.
Another way to fix it seems to be de-inlining the BitMatrix constructor

```
diff --git a/core/src/BitMatrix.cpp b/core/src/BitMatrix.cpp
index b4bc158..bd575c7 100644
--- a/core/src/BitMatrix.cpp
+++ b/core/src/BitMatrix.cpp
@@ -30,6 +30,10 @@
 
 namespace ZXing {
 
+#ifdef ZX_FAST_BIT_STORAGE
+       BitMatrix::BitMatrix(int width, int height) : _width(width), _height(height), _rowSize(width), _bits(width * height, UNSET_V) {}
+#endif
+
 void
 BitMatrix::getRow(int y, BitArray& row) const
 {
diff --git a/core/src/BitMatrix.h b/core/src/BitMatrix.h
index c6efab6..86899a1 100644
--- a/core/src/BitMatrix.h
+++ b/core/src/BitMatrix.h
@@ -79,7 +79,7 @@ public:
 #ifdef ZX_FAST_BIT_STORAGE
        static bool isSet(data_t v) { return v != 0; } // see SET_V above
 
-       BitMatrix(int width, int height) : _width(width), _height(height), _rowSize(width), _bits(width * height, UNSET_V) {}
+       BitMatrix(int width, int height);
 #else
        BitMatrix(int width, int height) : _width(width), _height(height), _rowSize((width + 31) / 32), _bits(((width + 31) / 32) * _height, 0) {}
 #endif
```

**Comment by axxel** [comment]
Thanks for reporting this and putting in the effort but something does not quite add up:

 1) I fail to see how the mentioned c++17 change has any effect on why your client code should suddenly not find the `ZXing::BitMatrix::UNSET_V` symbol anymore, especially since the same symbol is used inside the inline `set(...)` method that you also call from your client code.
 
 2) I tried to replicate your issue with the `ZXingReader` example by calling the `BitMatrix` constructor there and compiling it with both c++11 and c++14 and both work fine.

Could you maybe construct a minimal example with build instructions that replicates the issue?

Also, I tried to start a discussion in #128 with the goal of convincing @vkrause to replace this whole `QImagePureBinarizer` class with a single call to `ReadBarcode()` while being faster than what you have right now at the same time. I intend to completely remove that whole `LuminanceSource` / `BinaryBitmap` API to cleanup the code base further and remove unnecessary mem-copies. I'm mentioning that here, because it would also make your issue go away while prepping your project for a future ZXing release.

**Comment by axxel** [comment]
I just saw that your project switched to c++17 for good because of this. I guess your problem is therefore 'fixed'. I was curious what might have caused your issue but understand that this is not important enough for you to spent more time on.

I hope my hesitance to simply merge the PR was not off-putting and you will still consider contributing in the future ;).
