### ISSUE TITLE
emscripten build (windows, visual studio 2019)

### ISSUE THREAD

**Issue by anauta00** [nu-book/zxing-cpp#160]
Hi,

I am trying to build the wasm version of your (nice!) library.
However, I always get this error:

`emcmake cmake -G "Visual Studio 10" ..\..\..\wrappers\wasm
configure: cmake -G Visual Studio 10 ..\..\..\wrappers\wasm -DCMAKE_TOOLCHAIN_FILE=D:\Sources\Repos\emsdk\upstream\emscripten\cmake\Modules\Platform\Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR="D:/Sources/Repos/emsdk/node/12.18.1_64bit/bin/node.exe"
CMake Error at D:/Sources/Repos/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake:131 (message):
  Failed to fetch compiler version information with command
  "'D:/Sources/Repos/emsdk/upstream/emscripten/emcc.bat' -v"! Process
  returned with error code 2.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:3 (project)

CMake Error at CMakeLists.txt:3 (project):
  Failed to run MSBuild command:

    C:/Windows/Microsoft.NET/Framework/v4.0.30319/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 4.8.4084.0
    [Microsoft .NET Framework, version 4.0.30319.42000]
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 23/09/2020 12:11:28.
    Project "D:\Sources\Repos\zxing-cpp\build\wrappers\wasm\CMakeFiles\3.18.2\VCTargetsPath.vcxproj" on node 1 (default targets).
    D:\Sources\Repos\zxing-cpp\build\wrappers\wasm\CMakeFiles\3.18.2\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
    Done Building Project "D:\Sources\Repos\zxing-cpp\build\wrappers\wasm\CMakeFiles\3.18.2\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "D:\Sources\Repos\zxing-cpp\build\wrappers\wasm\CMakeFiles\3.18.2\VCTargetsPath.vcxproj" (default target) (1) ->
      D:\Sources\Repos\zxing-cpp\build\wrappers\wasm\CMakeFiles\3.18.2\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.15

  Exit code: 1

-- Configuring incomplete, errors occurred!`

Running 'emcc.bat -v' manually does not give any errors, so I am at a loss here.
Can you help?

Greetings,
Auke Nauta

P.S.
Output from 'emsdk_env.bat':
`Adding directories to PATH:
PATH += D:\Sources\Repos\emsdk\node\12.18.1_64bit\bin
PATH += D:\Sources\Repos\emsdk\python\3.7.4-pywin32_64bit
PATH += D:\Sources\Repos\emsdk\java\8.152_64bit\bin

Setting environment variables:
EMSDK = D:/Sources/Repos/emsdk
EM_CACHE = D:/Sources/Repos/emsdk/upstream/emscripten\cache
EMSDK_NODE = D:\Sources\Repos\emsdk\node\12.18.1_64bit\bin\node.exe
EMSDK_PYTHON = D:\Sources\Repos\emsdk\python\3.7.4-pywin32_64bit\python.exe
JAVA_HOME = D:\Sources\Repos\emsdk\java\8.152_64bit`

**Comment by huycn** [comment]
Hi Auke,

In the title you says VS 2019 but on command line, you pass -G "Visual Studio 10" which is VS 2010. You may want to try -G "Visual Studio 16 2019" instead?

That said, from what I know, Emscripten doesn't support VS toolchain but LLVM/Clang only. It may have changed recently but otherwise, you'll have more chance without -G parameter. Other alternative is to install emscripten and build project inside WSL.

**Comment by anauta00** [comment]
Hi huycn,

Thanks for your quick reply!

I tried with the "Visual Studio 16" parameter as well as leaving out the "-G" parameter altogether.
The results are always the same, error at line 131...

I am quite new to this wasm stuff.
Could you point me in the right direction as to how to build the wasm version of zxing-cpp on a Windows machine?
I do not mind to use different toolchains.
And what do you mean by "build project inside WSL"?

BTW, I have emscripten installed.

Thanks and greetings,
Auke

**Comment by huycn** [comment]
WSL is Windows Subsystem for Linux that comes with Windows 10. With WSL, you will get a fully functional Linux distribution (except XServer and GUI stuffs) running on top of Windows. You will find many guides on the web how to enable it. Once you are inside Bash, you can follow instructions in README to install Emscripten SDK and then build the project.

By the way, are you building wasm wrapper to customize the reader/writer, aren't you? Otherwise, you can just grab artifacts from our most recent [CI build](https://github.com/nu-book/zxing-cpp/actions?query=workflow%3ACI) and then extract `zxing_reader.wasm` and `zxing_reader.js` (or `zxing_writer.js` and `zxing_writer.wasm` if you need writer) and put them alongside with your webpage and you are ready to go.

**Comment by anauta00** [comment]
Well, I might want to customize things, but I really (first) would like to know how to make a functional wasm build.
In the near future I would require many libraries in that format.
At the moment I am just learning (although I am old, I am trying...)

Thanks and greetings,
Auke

**Comment by huycn** [comment]
The hard part is to setup emscripten, as you can see from our [CI build script](https://github.com/nu-book/zxing-cpp/blob/master/.github/workflows/ci.yml#L66-L70), once it's done, it takes only two lines to build. Luckily, others have done good job for this part, you may want to look into their script: https://github.com/mymindstorm/setup-emsdk/blob/master/src/main.ts.

**Comment by axxel** [comment]
Can this be closed?
