### ISSUE TITLE
Reduce the number of header files installed with make install?

### ISSUE THREAD

**Issue by hjmallon** [nu-book/zxing-cpp#168]
I am just evaluating this library so far, so please shout if this is way off mark.

When doing `make install` current zxing-cpp installs every header into the output tree. I would have thought that many of these headers are not 'public APIs' and therefore should not be used.

Would it be possible/sensible to thin out the header tree to only include headers which contain public functions and headers required to use them?

**Comment by axxel** [comment]
You are right that this behavior is 'unusual' and it does expose all internals, which is non-ideal from a refactoring perspective. The reason is mainly that this project started out as a 'one man show' by @huycn who, in the beginning, considered it to be a 'copy the source code' kind of project. There has simply no one been interested in doing the work of splitting the headers into public and private.

That said, now is actually not a good time to start doing that. The reason is that there is code out there using what I consider the 'old' API (see `MultiFormatReader`, `GenericLuminanceSource`, etc.) instead of the 'new' one (see `ReadBarcode.h). I'm in the process of deprecating that 'old' API. Once the few existing downstream projects don't use that anymore, we can remove/hide all those internals and ideally only provide something like a single-function API to the whole (reader-)functionality. Then the number of public headers will go down to a handful.

May I ask what your specific issue is with the current approach?

**Comment by hjmallon** [comment]
I guess my specific issue is that I want to know which functions are current and will be supported into the future. I don't want to accidentally rely on some implementation detail or deprecated API, I would normally evaluate this in a library by checking:

* Which headers are public (I would expect these to be installed with make install or similar)
* Which functions are specifically deprecated (via docs or decorators)
* Which functions are exported and which are hidden in a dynamic build

**Comment by axxel** [comment]
Very sound approach ;). If you are interested in reading/decoding barcodes, please start with the `ZXingReader` example and if you feel the need to get more access than provided through the single `ReadBarcode.h`, let me know.

**Comment by hjmallon** [comment]
I think I will need reading and writing. I am starting with the writing. I assume `MultiFormatWriter` is current there? To be honest I may want to use the QRCodeWriter directly.

**Comment by axxel** [comment]
> I assume MultiFormatWriter is current there?

Yes. I have not thought about or done much with the writer side of the equation. There is definitively work to be done, e.g. the quite-zone generation behavior is inconsistent across the set of writers. If we come up with a 'unified/simple' API it will likely not be the current MultiFormatWriter. So, you may as well use the QRWriter directly.
