### ISSUE TITLE
QR Code Model 1 not supported

### ISSUE THREAD

**Issue by zhangyouchun** [nu-book/zxing-cpp#174]
![IMG_20201127_140634](https://user-images.githubusercontent.com/33076311/100418579-f6a6a280-30bd-11eb-9e8d-5751a4ec832e.jpg)

**Comment by axxel** [comment]
This examples fails to get detected because of 2 things:

 1) The resolution is too high for the default binarizer (`LocalAverage` or `HybridBinarizer`) to properly separate blacks from whites.
 2) This is a Model 1 QRCode, that means the original / obsolete variant.

Most readers can't decode Model 1 codes. I will not work on supporting them either. Maybe someone else will? Where did you find this?

**Comment by zhangyouchun** [comment]
Thanks

**Comment by zhangyouchun** [comment]
> This examples fails to get detected because of 2 things:
> 
> 1. The resolution is too high for the default binarizer (`LocalAverage` or `HybridBinarizer`) to properly separate blacks from whites.
> 2. This is a Model 1 QRCode, that means the original / obsolete variant.
> 
> Most readers can't decode Model 1 codes. I will not work on supporting them either. Maybe someone else will? Where did you find this?

Do you know any libraries that support model1？

**Comment by axxel** [comment]
While trying to find out what kind of code that is (I did not know about Model 1 vs Model 2 when reading about your issue), I tried random online QR Code decoders and found that worked. I believe they also have a commercial library available. But forgot which one it was. The search engine of your choice should help you find something. Whether there are open source alternatives available, I don't know either.

**Comment by kuangguo** [comment]
支持model1的库找到了吗

**Comment by kuangguo** [comment]
Have you found the library that supports model 1？

**Comment by axxel** [comment]
This image can now be successfully decoded.
