### ISSUE TITLE
viddemo: support for selecting camera

### ISSUE THREAD

**Issue by mfulton26** [nu-book/zxing-cpp#177]
I find on my Samsung Galaxy S10e that the viddemo does select an environment facing camera but one that is a bit zoomed out while there is another that is more zoomed in

for showing this library to coworkers and others, etc. it would be great if there were a `<select>` tag or something similar to select which camera to use

(I suspect it will pick up Code 128 barcodes better like on iOS when zoomed in more.)

Thank you.

**Comment by axxel** [comment]
I don't know what you mean by 'viddemo'.

**Comment by mfulton26** [comment]
https://github.com/nu-book/zxing-cpp/blob/gh-pages/zxing_viddemo.html

**Comment by mfulton26** [comment]
linked to from the README: https://nu-book.github.io/zxing-cpp/zxing_viddemo.html

**Comment by axxel** [comment]
Ah, right. I forgot about that one. I checked the link down in the WASM section of the readme to https://nu-book.github.io/zxing-cpp/ but that does not contain a link to the video demo page. The thing is, these 'live' pages are actually not part of the repository. There is a reader and a writer example in the WASM folder that were based on those live pages but they are pretty outdated by now.

They were authored and setup by @huycn. Maybe he could setup the CI such that they get updated automatically.

About your request for a camera selector: sounds like a good idea but I'm not a web developer... ;)

**Comment by huycn** [comment]
I added a select in viddemo page which allow us to choose which camera to use.

FYI, demo pages and their resources (js, wasm, etc.) could be found in this repo but in another branch, [gh-pages](https://github.com/nu-book/zxing-cpp/tree/gh-pages). They were put into another branch instead of inside "docs" folder (which is other way to create GitHub Pages) as they contain large binary files that are not used in others contexts.

I will change the ci workflow to updates these files automatically as axxel suggested.

**Comment by huycn** [comment]
@mfulton26 Also, your rear camera is likely to be able to do auto focus, try to tap inside the video where your barcode is.

**Comment by axxel** [comment]
> I will change the ci workflow to updates these files automatically as axxel suggested.

In the light of the information that those wasm files are actually checked into this repository (which I discovered at some point in time but forgot again ;)), I'd strongly suggest to _not_ automatically update them via the ci workflow. This project's git repo is already unpleasantly huge (250MB) due to all the sample images (I recently removed a bunch of them to reduce the tarball size but the repo history does of course still contain them).

I believe there should be a better solution for hosting those binary files, but I would have to search for one myself...

**Comment by huycn** [comment]
I agree with axxel to not update demo binary files from ci workflow. Camera choice had been added to demo page, thus I close this issue.

**Comment by mfulton26** [comment]
Thank you!
