### ISSUE TITLE
DataMatrix is missing support for flipped/mirrored symbols

### ISSUE THREAD

**Issue by gloomyfish1998** [nu-book/zxing-cpp#195]
i need to display DM decode result as hex code in my project/? 
but i convert to hex string directly,  get wrong decode result as hex string/?

please any advice, how to get hex code string with rawbytes

**Comment by axxel** [comment]
I don't have advice for how to convert bytes to a hex string. If you have a specific DM image with a decoding issue, feel free to post it here. In that case, also include the expected output, please.

**Comment by gloomyfish1998** [comment]
![20210203110247882_S0_D0](https://user-images.githubusercontent.com/30948147/107113056-444a4300-6897-11eb-842a-071178788aa6.jpg)

**Comment by gloomyfish1998** [comment]
please verify this pic, ZXing could not recognize at all~~~~~~,

**Comment by axxel** [comment]
This image has two issues:
a) it is inverted. you need to invert before feeding it to ZXing.
b) it is a dotted matrix, which is not (properly) supported. See #53.

**Comment by gloomyfish1998** [comment]
i got it now~~~~
thanks a lot~~~~~~

**Comment by gloomyfish1998** [comment]
![image_grad](https://user-images.githubusercontent.com/30948147/107117380-f93f2880-68b4-11eb-8d20-754c68ca9848.png)

**Comment by gloomyfish1998** [comment]
i still could not prase this code ~~~~, it is not dotted now~~~~~, can you verify this/?

**Comment by axxel** [comment]
That is a tricky one. The symbol is not only dotted and inverted, it is also flipped (photographed from the back side). And it seems to contain a broken (or unsupported) ASCII encoding. After flipping it horizontally, some online decoders can decode it but ZXing fails because of an 'invalid' raw byte value (246). Do you know what the expected result is?

**Comment by gloomyfish1998** [comment]
hi, thanks your feedback!
this is the result :76;z5273o48
now we need to decode the rawbyte, the unsigned char 246 should be valid one, 
in my case,
is there any workaround with ZXing, we can get still get raw bytes whatever the code is invalid or valid, 
please advice us, thanks ~~~

another question
which cpp file is related to this issue in ZXing ,we can modify it locally and recompile it to support, any suggestion/?

**Comment by gloomyfish1998** [comment]
![9010_flipy](https://user-images.githubusercontent.com/30948147/107137400-16bcd280-6947-11eb-93f0-2eed4c64f89f.png)
another one that ZXing could not recognize, it is very clear image~~~~

**Comment by axxel** [comment]
> is there any workaround with ZXing, we can get still get raw bytes whatever the code is invalid or valid

Yes there is: if you comment out https://github.com/nu-book/zxing-cpp/blob/55671e5993b677ddeda2ed3cefd9644db330a1c8/core/src/datamatrix/DMDecoder.cpp#L165 you get your expected ASCII result and the 'invalid' 246 is simply ignored during the raw->text conversion.

> another one that ZXing could not recognize, it is very clear image

that is not a valid DataMatrix symbol. Both the top row and the right column need to contain a 1 module wide alternating black/white pattern. The right-most column is wrong here.

**Comment by gloomyfish1998** [comment]
thank you very much!

**Comment by axxel** [comment]
I added support for mirrored/flipped symbols for now but I'm wandering where your sample came from. I've never seen a flipped DataMatrix before. Do you know why your image is that way?

**Comment by gloomyfish1998** [comment]
> I added support for mirrored/flipped symbols for now but I'm wandering where your sample came from. I've never seen a flipped DataMatrix before. Do you know why your image is that way?

becasue the cam make these images in machine vision , it is very common case!

**Comment by enzo-simone** [comment]
Sorry but for what it is worth I do no agree with you @gloomyfish1998 .

If you are doing computer vision you are processing your images (if not even control your image sources) so if in your environment you can have flipped images it is your onus to flip them back to normality.

I.M.H.O. this should remain a library with the sole responsibility to decode barcodes, not preprocess images.
The unique preprocessing which should fit in the library is binarization which is functional for decoding, and preprocessing may help for out-of-focus and/or differently illuminated barcode areas (e.g. using local thresholding).
But again this is a nice-to-have not a must.

@axxel sorry not to be able to figure out myself: with proposed [changes](https://github.com/nu-book/zxing-cpp/commit/8f2a2d94d50a6757a95cbb7ffba45847f82267aa) am I still able to refuse decoding of flipped barcodes?

**Comment by axxel** [comment]
@enzo-simone No, my latest change does allow you to refuse to decode flipped DataMatrix symbols. I was considering adding a flag to `DecodingHints` but it seemed not worth it since the runtime overhead of this change is negligible. May I ask why you would care to prevent the detection of flipped symbols?

Regarding the general question of whether or not this auto-flipping belongs in the library I would argue that it generally does if it is not totally useless and therefore a pure waste of energy. For example the `QRReader` does this as well and I can imagine real world scenarios where it is really useful, e.g. you can easily photograph a QRCode printed on paper and taped to a glass door from the backside. Or we recently added flipped symbol support for PDF417 because some drivers licenses have them printed vertically flipped (for whatever reason). I was just curious under which circumstance a flipped DataMatrix would appear in the real world. If a specific application captures images through a mirror, then I would also argue that the problem is more adequately solved by flipping the image by the user of the library to revert the mirroring.

**Comment by enzo-simone** [comment]
@axxel I work in Computer Vision too, and I use Datamatrix to locate objects in a scene: what if library tells me there is a sought object in a certain position whether instead that is just a reflection on a polished surface? ;)
At least I would like to know if the decoded Datamatrix is flipped or normal in the result.

My use case is:
 - grab image
 - preprocess as needed
 - ask the library if any sought Datamatrix is found

If my camera is watching through a mirror I know I have to flip images during preprocessing, or configure the camera to return flipped images to save CPU time.

Sadly, often I have also to binarize images before trying to decode because of non uniform illumination (the already cited local thresolding stuff).

**Comment by axxel** [comment]
@enzo-simone That sounds interesting. I see your point. Yes, the current code needs to be changed to support your use case. I'd still like to learn from @gloomyfish1998 how this mirrored input actually comes to be.

I might go with the 'quick fix' and simply comment out the new code again. Since @gloomyfish1998 needs a custom build for the invalid ASCII character a.t.m. anyway, he can enable the flipping in his build.

Another thought: if you can control the symbology in your tracking application, I would go with QRCodes, they are way easier (i.e. faster) to locate if you need to search the whole image.

**Comment by enzo-simone** [comment]
Thank you @axxel, unfortunately I inherited a code base where DataMatrix was chosen, nevertheless I will use your suggestion to QRCodes whenever it will be possible or for future projects.

I think a 'try-to-flip-image' hint is just how we are used to configure the library and also in the spirit of the zero-overhead™ principle.

**Comment by axxel** [comment]
Closed with this commit: 3836f4c998bf059a643cb2e59ad35a96f02bd40b
