### ISSUE TITLE
Releasing python wrapper on pypi

### ISSUE THREAD

**Issue by antoinehumbert** [nu-book/zxing-cpp#204]
Hi,

I'd like to know if you have any plan for officially releasing wheels of the zxing-cpp python wrapper on pypi.org ?

I can see that wrapper is considered experimental in the readme file. What is missing to consider it stable for official release ? How can one help / contribute in order to achieve the goal of official releases (if this is in your plan) ?

Thanks for your answer

**Comment by axxel** [comment]
Thanks for your offer to help improving the project. There is currently no plan to officially release wheels on pypi.org. That said, I would personally welcome that. I don't have any experience in doing that and it would not happen without help from the community.

I'd consider the wrapper experimental mostly because I don't see the current API being 'future proof'. I'd generally prefer if the different wrappers and the main-line C++ API were consistent and ideally equally capable. But it also makes sense to me to use an API that feels natural/native in the respective language. The read function for example has a set of parameters that naturally split into 2 sets: a) the image (the data and its layout/format) and b) the (optional) decoding parameters. The latter is typically modeled as an object in Android, which is why we have this `DecodingHints` class here and I consider it a good approach compared to a single function with a ton of parameters.

The current python wrapper goes the single parameter route though, but is currently limited to the most basic set of 'hints'. The question would be how to go about that in a pythonic way. Optional named parameters or a dictionary? Suggestions?

Looking forward to your feedback.

**Comment by antoinehumbert** [comment]
Well, I see what you mean. May be it would be better for the zxing-cpp project to have wrappers as close as possible as the c++ API in order to make it easier to maintain when something changes in the C++ code.

However, providing APIs that are more "language friendly" is also probably better for adoption by "final" users.

So, there are probably two API levels to propose : the "C++ main-line" one and the "pythonic" one. The first being in the wrappers of zxing-cpp. The latter may be in the same project, or another one : I'm in doubt about that.

I'll try to make some proposals for that in a pull request. Just one question before starting some wrok : are you attached to the use of pybind11 for the binding, or would it be acceptabe to use cython ? I know the first one is usually prefered by cpp developpers and the latter by python developpers.

**Comment by axxel** [comment]
I'd prefer the following:
1) have one python module/API that feels "pythonic" and supports all current features of the `ReadBarcode` API
2) stick to pybind11
3) anticipate the following future improvements:
  * more options controlling the detection
  * return results for multiple symbols from one call
  * extend the `Result` with more information (like e.g. a `flipped/mirrored` flag)

I don't have much of an opinion about the writing part of the lib, other than it would ideally be 'symmetric'. Which is not the case on the c++ side, yet.

Any comments from the other python users (@timrae @urishab @dimatura @hbaocr @TransparentLC)?

**Comment by urishab** [comment]
I have some thoughts about that, thanks for asking:

1. Regarding reading options I think there's space for a lot more options. e.g. min/max barcode length. 
2. DecodingHints does not feel pythonic at all but I would be fine with a wrapper function that sets all the relevant hints and then runs the decoding part using DecodingHints. It should have all hints as keyword options. It's an easy enough solution.
3. I would love if the library would support returning multiple codes. Even if it only had partial implementation at first. I was looking inside the code and saw that datamatrix reading was very amenable to returning multiple codes with an efficient algortithm. Reading multiple codes could work for some codes and raise NotImplemented for others.
4. Extending Result also makes sense to me. Some parameters come for free and there's no reason not to include them. All high-end barcode readers do this. e.g. barcode size (pixels / line or pixels / square) comes freely from the decoding.

**Comment by TransparentLC** [comment]
Thanks for asking and I think it would be great if the wrapper could be more friendly for users.

For example, the current `zxing.read_barcode` only accepts cv2 images. However, if I want to read barcodes in a PIL image, using `zxing.read_barcode(PIL.Image.open(...))` is better than manually converting the image to cv2 format before decoding. I guess that the PIL image can be converted to raw pixel data inside the wrapper without modifying any C++ code.

**Comment by antoinehumbert** [comment]
The following branch is a first implementation of what was discussed above : [https://github.com/antoinehumbert/zxing-cpp/tree/feature/python_bindings](url)

It implements a binding for DecodeHints and add a read_barcode2 function (which may replace the read_barcode function) using the same API as C++ ReadBarcode (i.e. image + hints)

The bindings are exported in a zxing._zing module and the zxing python module (zxing.__init__.py) exposes some of the binded classes and functions but also defined some more pythonic interface (i guess) :

- the DecodeHints python class can be instanciated (or instances can be updated) from keyword arguments (converting from snake case names which is the python standard to camel case as defined in the C++ API)
- the "formats" of DecodeHints instances can be defined using a BarcodeFormat instead of BarcodeFormats, avoiding for the user the boilerplate of doing BarcodeFormat.QRCode | BarcodeFormat.NONE

- the read_barcode2 accepts PIL images as well as cv2 images

It actually lacks some documentation, ... but I'd like to have your feedbacks before going further.

Regards

**Comment by axxel** [comment]
@TransparentLC: the current `read_barcode` requires a numpy array as image input and does therefore work just fine with PIL images, see e.g. [demo_reader.py](https://github.com/nu-book/zxing-cpp/blob/master/wrappers/python/demo_reader.py)

@antoinehumbert thanks a lot for your effort. I had a quick look and here are some thoughts:
 * the extra PIL handling should not be necessary (see above)
 * the `TypeError: read_barcode(): incompatible function arguments.` when passing a single `BarcodeFormat` is actually an oversight of the current implementation. The C++ class `BarcodeFormats` can be happily constructed from a single `BarcodeFormat` and I did not realize that the python class does not support/wrap that constructor. There should be a fix for that in the pybind11 module.
 * the kwargs based constructor of `DecodeHints` should also be implementable within the pybind11 module (says my gut feeling ;)), hence we might not need this split into a python and a cpp module, right?

I can see how having a python part involved may make it easier and more convenient to add stuff down the line (like the PIL handling if it were necessary) and within a wheel it would not make a difference for the user anyway. But right now it seems to me it unnecessarily bloats the code? Please don't hesitate trying to convince me that it is worth it ;).

**Comment by antoinehumbert** [comment]
- for PIL Image, when not in L mode, I think there would be some different results because cv2 color images are usually BGR (as stated in the read_barcode implementation) whereas PIL Images are RGB.
- for your other remarks, I may have a look at it next week. I need to read more about the pybind11 documentation, in particular for the case of keyword arguments.

**Comment by axxel** [comment]
I was not aware of this discrepancy between PIL and cv2 images. I did a little experiment and your trick to determine the type of the object can be replicated inside the pybin11 module and it would allow to omit the extra buffer copy that your 'L' conversion performs.

Also there are only very few and wierd circumstances where it would actually make a difference if R and B channel are reversed. So I'd claim this is not even worth the hassle.

**Comment by axxel** [comment]
Question: what is the most 'pythonic' way to call the `read_barcode` function with a bunch of optional parameters? I don't think explicitly creating a `DecodeHints` object is the answer. Maybe just stick with a simple function with (a lot of) optional named parameters, like
```Python
r = read_barcodes(img, formats=BF.EAN8, tryHarder=true, requireEanAddOnSymbol=true)
```
I believe we'd do the same in c++ if we had the possibility of named parameters. Once we have c++20 we can sort of get there with named initializers of simple structs:
```C++
r = ReadBarcode(img, {.formats=EAN8, .tryHarder=true, .requireEanAddOnSymbol=true})
```
whereas right now the most concise way is
```C++
r = ReadBarcode(img, DecodeHints().setFormats(EAN8).setTryHarder(true).setRequireEanAddOnSymbol(true))
```
So in C++ (and I guess Java) there is simply no alternative to this `DecodeHints` thing in the API. There is also a value of this struct to pass on / store those parameters internally (instead of having to name all the members multiple times). So if there was a common use case inside python clients to pass on / manage this set of parameters as a whole, then mapping the struct might make sense. So, how are you python people using the library? :)

And yes, this is sort of contradicting my first comment in this discussion. But finding the best approach through discussion was exactly the point ;). Am I overlooking something?

**Comment by antoinehumbert** [comment]
Here are my thoughts about the PIL usage :
- I think that not converting to "L" within PIL will just delay the new buffer creation to the GenericLuminanceSource constructor that will create a new buffer when converting in RGBToGray. If we pass directly a "gray" buffer, then GenericLuminanceSource will directy use this buffer (if I understand well the "std::make_shared<ByteArray>(pixels);" in the MakeCopy - sorry, I'm not a big C++ expert)
- Regarding the order of RGB channels, even if cases where it may make a difference are not so common, I consider that RGB is definitly not the same as BGR and if we have a simple mean to handle the difference, it should be. Thus, if identification of the "king" of image can be done on the pybind11 side, I will try to transfer thant in zxing.cpp. Here, doing it in the python world or in the cpp world is just a phylisophic consideration I think as I even don't think there would be a big performance impact : but if you prefer keeping the binding "cpp" only, I can adapt ;-)

For implicit conversion from BarcodeFormat to BarcodeFormats, your modification actually works with the BarcodeFormats constructor but after testing, I cannot make it work when using DecodeHint().setFormats(), so that you're example with DecodeHints().setFormats(EAN8) is not working for me. I think we have to create an override of the setFormats that will do the cast from BarcodeFormat to BarcodeFormats. I'll try to look at this on the pybind11 side.

For the signature of the read_barcodes function, I think that having keyword arguments is definitly more pythonic than giving it a DecodeHints object. But having an explicit list of keyword parameters or an **kwargs in the function definition is just a matter of correctly documenting the function I think.
One another thing about those keyword parameters is their spelling : if we conform to the PEP8, they should be in snake case, but it would require a mapping with the camel case attribute names for building the corresponding DecodeHint, that may be painfull to do on the cpp side.

**Comment by axxel** [comment]
ad "L": yes the performance impact will be most likely be negligible. But note: a) the GenericLuminanceSource with its internal copying of the whole buffer will go away (sometime) and b) moving the determination of where the image came from into the cpp part will allow to select the right `ImageFormat` instead.

ad RGB: I truly believe that this could reasonably be ignored for two reasons: a) barcodes are generally black/white, so R and B values will virtually always be about equal and b) we could simply define the color->greyscale function to be `(R+G+B)/3` but that would break a couple of test cases due to noise which is a bummer (and mostly points to the fact that decoding is not as robust as it should be) but it would not fundamentally be wrong.

If you want to still make 'right (TM)', here is my experiment in `zxing.cpp`:
```C++
Result read_barcode(py::object _image, const BarcodeFormats& formats, bool fastMode, bool tryRotate, Binarizer binarizer)
{
	std::cout << py::type::of(_image) << "\n";
	auto image = _image.cast<Image>();
```
If I call that with a PIL image, I see the "PIL" string on the console... What I did not find out is how to 'return' the correct error if I call that function with an object that can not be cast into a numpy array.

ad DecodeHints:  Then let us forget about the `DecodeHints` struct and simply add a bunch more optional parameters to the read_barcode function (in snake case). I had a look at the currently missing options would suggest to only add `is_pure` and `require_ean_add_on_symbol` for now and the rest is pretty 'esoteric' and adding them without anyone using them just adds cruft that needs to be cleaned up later on. Also adding one more default parameter later would not break any existing python code.

**Comment by antoinehumbert** [comment]
I just commited a new version in my personal branch for handling of PIL images in zxing.cpp. Can you review ?

Next, I will remove the DecodeHints parameter and move to keyword arguments (in snake_case), so that we could completly get rid of the zxing.py module I previously added.

**Comment by axxel** [comment]
That looks very good. I added a few comments. The support of RGBA and all other formats is an unexpected bonus. :)

**Comment by antoinehumbert** [comment]
Hi @axxel,

I just pushed some new modifications in my personal branch:
- add the new parameters mentioned above to the _read\_barcode_ function. I also renamed the _fast_ parameter to _try\_harder_ to be closer than the cpp API (let me know which one do you prefer)
- add stronger check of numpy arrays number of channels with a failure if there are not 1 or 3 channels (may be we could accept 4 channels in which case image should be considered BGRA mode ?)
- change parameter names of the _write\_barcode_ function to be PEP8 compliant (use snake case parameters names)
- add some docstrings with type hinting for helping when using the wrapper in IDEs. I'm not sure my understanding of the different parameters is correct, so please, could you have a review on this ? In particular:
  + what is the signification of margin=-1
  + I'm not sure that ecc_level is a percentage value as it looks it's not processed the same way for the different barcode formats.

Finally, I also completed the setup.py file to prepare release on Pypi and added 2 github actions for python unittests and build of wheels + publish on Pypi: I can explain in more details this if necessary (in particular, you will need a Pypi account with a token and set it in the secrets of the github project).
Note: I renamed the distribution from _zxing_ to _zxing-cpp_ because the _zxing_ distribution already exists on pypi. This does not change the name of the root package the distribution provides, which is always _zxing_.

There are 2 more things I'd like to add (I'll try to work on this next week):
- more unittests, in particular with use of the different parameters of both _read\_barcode_ and _write\_barcode_ functions
- use setuptools_scm for automatically defining the version of the python distribution so that it follows the same versioning as zxing-cpp itself and tagged versions.

**Comment by axxel** [comment]
* Regarding the tryHarder vs fastMode. I'm generally with you on this one but my explicit attempt to find interest for a consensus on this one did not bear much fruit: #104 :-/.
 * I'm happy with 1 / 3 numpy chanels right now.
 * there is an inconsistency: write_barcode -> eccLevel, Result -> ecLevel. My prior art search did not reveal an obviously 'correct' choice. The meaning of this parameter is barcode dependent and I believe this should actually be a str parameter and simply be format dependent. E.g. QRCode levels are named L/M/Q/H. The writer-side of things is pretty inconsistent between formats at the moment. But since I don't have a clear picture where this should end up, we should probably just leave it as is for now.

Excuse my ignorance but I found the following 3 decisions questionable, mainly because my gut feeling tells me that there should be a better way (let me know if you are convinced that there is not ;)):
 * gitignore: I would think there is a better way (out of source build) than flooding this file with a ton of python specific files?
 * pre-build-manylinux.sh: is that really best practice? I would hope that a `pip wheel` build would be able to cope with how every modern cmake project is built? I have no experience with packaging python modules, though.
 * python testing: is that best practice / necessary to build and test the module on 3x4=12 configurations? I wonder whether that might be a waste of resources?

**Comment by antoinehumbert** [comment]
- gitignore: entried I added are typical for python projects. Indeed, when created a new project on github using the python template for gitignore, you will get such a file. May be I should just set this gitignore in the wrappers/python directory instead of project root. What do you think about this solution ?
- The problem here is that pip wheel uses a temporary directory when building python project and for that reason the "link" to "core" directory is broken inside this temporary directory because it's above the python directory. Using python -m build does not have this problem (see the builds for windows and macos). Also, using editable mode (pip wheel -e .) also works, but here the problem is that the github action used (RalfG/python-wheels-manylinux-build@v0.3.3-manylinux2010_x86_64) does not allow me to use such an option. I may submit an issue to RalfG for this, but patching the CMakeLists.txt file for this specific build is the only workaround I found for now.
- building and testing against different configurations ensure that everything is working fine for each configuration. For pure python distributions, this may not be really necessary but here, we are not pure python so if we want to release some wheels, we have to build a different wheel for each python version / platform. This is the same for example for numpy : [https://pypi.org/project/numpy/#files](url). If we want to limit the number of configuration, we can limit python versions we support to the 3 last one only (3.7 to 3.9). It would also be possible to distribute only a source package, but in this case, users will need to install dependencies such as cmake, a compiler (vc++, gcc, ...) before being able to use the python wrapper. Distributing wheels can be thought as distributing an already compiled version of the library in the same maner as providing .deb, .rpm, ... packages for linux distributions instead of a .tgz of the sources the user will have to compile by himself.
  Finally, I let you the choice of the targeted audience for python releases, and adapt the test/build configurations accordingly

**Comment by axxel** [comment]
First of all: thanks for detailed info. Very much appreciated.

* .gitignore: yes, please :)
* per-build-manylinux: I obviously don't know enough about how this is supposed to be done. Question: if `python -m build` on macos does not have the issue, then why not use the same technique on linux?
* testing: publishing packages including the *.so file is certainly more userfriendly. if numpy is limited to the last 3 then this choice seems reasonable?

Having had a closer look at your proposed workflow files and the linked doc (https://docs.github.com/en/actions/guides/building-and-testing-python) resulted in more questions. I'd like to suggest the following approach: let's first merge the fixes/improvements to the module itself and then discuss my remaining workflow questions inside a second PR.

**Comment by antoinehumbert** [comment]
Hi,

I just created a PR.

I changed the build workflow for use of cibuildwheel: seems more used for build of python prjects with compiled C extensions.

Regarding the problem of path pointing "out" of the python project root, this is solved by the last modifications in CMakeLists.txt. This modification make sense because we should consider being able to build the "python part" of the project without access to the C++ repository part: this would be the case when building from the published source distribution. I can explain this in more details if necessary...

**Comment by axxel** [comment]
Since the recent python related changes are somewhat breaking the API (`tryRotate` -> `try_rotate`, `fastMode` -> `try_harder`, etc.) and since after two years I'm still unhappy about the whole `tryHarder` situation, I wonder whether it would not be better to drop this parameter from the API before we release it on PyPi and reintroduce it once I found something more 'future proof' (again, see #104 for details). This would prevent another breaking change down the line.

Question to the Python 'community' (@timrae @urishab @dimatura @hbaocr @TransparentLC): Is anyone using the library in "fastMode / tryHarder=false"?

**Comment by timrae** [comment]
I support removing the parameter as well

**Comment by TransparentLC** [comment]
I'm not using that option.

**Comment by urishab** [comment]
I also always have it at tryHarder=True

**Comment by axxel** [comment]
@antoinehumbert I'm about to release version 1.2 and publish the first PyPi package. Is there something on your list that you would want to add/change before that?

**Comment by antoinehumbert** [comment]
Everything looks ok for me. May be the "expermimental" status of the python wrapper should be removed before releasing on pypi !

**Comment by axxel** [comment]
Before the release, there are two more things I'd like address:

 1) The current code/discussion suggests to publish a PyPI package called `zxing-cpp` that contains a module called `zxing`.
Given the list of PyPI packages related to zxing (https://pypi.org/search/?q=zxing&o=), I wonder whether it would not be best to change the name of module since that would conflict with at least the `zxing` package on PyPI. Module names with a dash are a no-go. So that would leave either `zxingcpp` or `zxing_cpp` as two 'obvious' choices. I'd appreciate if someone could provide a reason why one would be better than the other of why I'm wrong with doubting `zxing` as the module name.

 2) @timrae you placed your name and e-mail address in the `setup.py`. If you don't mind, I'd like to replace that with something 'generic' like 'zxing-cpp community' and the newly created non-personal email address zxingcpp@gmail.com. The latter can be setup to forward any e-mails to whomever is interested.

**Comment by timrae** [comment]
@axxel Yes absolutely :) I'm not working in this area anymore, but thanks for your continued work on this project!

**Comment by axxel** [comment]
ad 1.: the WinRT module is also called 'zxingcpp' as well as the new Android library I recently added. And I checked what happens if you installed both `zxing` and `zxing-cpp` (see https://test.pypi.org/project/zxing-cpp/1.2.0/): `import zxing` gets you the first without any hint of a name collision.

I'd also appreciate some feedback if the above test.pypi module works also on windows and macos before I release it to the real PyPI.

**Comment by antoinehumbert** [comment]
Successfully tested on Windows.

Regarding the name of package: using the same name as zxing distribution (based on java zxing, calling zxing through command line) would not be a problem if there were no chance that someone use both distributions at the same time.

Why may someone use both at the same time ?

- Java zxing and Cpp zxing may have diverged a lot and both give some different results I'd like to combine, or use one or the other depending on its capabilities (e.g. reading multipe barcodes on the same image vs. one or using one for Datamatrix and the other for others kind of barcodes)

Why I wouldn't use both at the same time ? (this is my opinion that may not be objective and is closer to "why I would not use zxing Java wrapper")

- Java zxing wrapper is clearly not an "advanced" wrapper : wrapping the command line only has many drawbacks:
  + it does not give you access to the whole functionalities of the library
  + it has the penalty time of starting a new JVM for each new image you want to read
  + it extracts results from the command line output in binary mode without any decoding of text character set so that I'm pretty sure I may have some breakage if I tried reading some barcode with non ascii characters, depending on the execution environment.

However, if the WinRT and Android library both uses the zxingcpp name, it may be more consistent to use it also for python library.

Finally, if you change the name, you will have to update the readme sample. If so, I would also suggest to update the Install procedure which just consist in calling "pip install zxingcpp" (and not "python setup.py install" which would only be used if installing directly from the sources and not from pypi)

**Comment by axxel** [comment]
@antoinehumbert thanks for the windows test and your feedback about the naming. I also don't think people would use both in production (mainly because I'm convinced that zxing-cpp is way superior (which I have to think after all the time I spent working on it ;))). But what I can imagine is that someone would want to play with both to find out which is better. I'm going to change it to `zxingcpp` then. One can always simply `import zxingcpp as zxing` if one wants to.

**Comment by axxel** [comment]
After being practically offline for 6 weeks, I've finally come around to call the current code 1.2.0 and publish the build on PyPI. Thanks for all involved, especially @antoinehumbert.
