### ISSUE TITLE
Who uses BYTE_SEGMENTS from the ResultMetadata class?

### ISSUE THREAD

**Issue by axxel** [nu-book/zxing-cpp#211]
Last stop would be the `BYTE_SEGMENTS` key. Note, this is not the `rawBytes` data that is already available in `Result` directly but rather an even more low level set of bytes that is very format specific. I have no idea what this data could be useful for at all...

See also #210.

**Comment by tailsu** [comment]
We don't use byte segments. I think it's improperly designed. DataMatrix can contain a mix of text and binary. The byte segments then contain the binary bits, but there is no parallel structure that contains the text bits, so you can't really derive the complete structure of the barcode. That's why we use just the raw bytes.

**Comment by axxel** [comment]
For lack of use/interest, this feature will then be removed without replacement.
