### ISSUE TITLE
ITF detection fails with partial symbol before complete symbol

### ISSUE THREAD

**Issue by LugPaj** [nu-book/zxing-cpp#220]
For test1.png, the ITF barcode is detected nicely. For test2.png the barcode detection fails. Test2.png is pixelwise the same image as Test1.png, but with some additional pixels black, below the barcode, but with a huge gap to it. 

I think those pixels are so far away, they shouldnt influence the barcode detection, therefor i consider this as a bug. 
![test2](https://user-images.githubusercontent.com/81755740/114164065-2b0f5280-992b-11eb-9c0d-20ed6eeb17c7.png)
![test1](https://user-images.githubusercontent.com/81755740/114164070-2ba7e900-992b-11eb-9a25-43b106cbd025.png)

**Comment by axxel** [comment]
The problem with this code is that the extra pixels form a valid starting pattern of an ITF code. The reader then stops because the pattern is not long enough. But then the rest of the line gets discarded and it never finds the second (valid) ITF code. This is a limitation of the current implementation that is on my TODO list for a while now. It is the same limitation that prevents detecting multiple barcodes of the same type in one row (see also https://github.com/nu-book/zxing-cpp/issues/138#issuecomment-652820490).

**Comment by LugPaj** [comment]
Actually i do barcode scanning from rendered pdf documents. The above are just reduced pdf pages rendered at 150dpi (which seems to work nicely overall). The faulty 3 lines are just the beginning of another barcode, but this one was somehow corrupted by other pdf processing, before i got the pdf. So it would be great, if those buggy barcodes can be skipped :).
