### ISSUE TITLE
Which alternatives for deprecated functions?

### ISSUE THREAD

**Issue by Portiella** [nu-book/zxing-cpp#235]
Hi,
what alternative to use for?

ZXing::DecodeHints hints;
hints.setPossibleFormats(codebars);         // <<<<<<< deprecated
...

ZXing::Result result(ZXing::DecodeStatus::NoError);
... result.resultPoints() ...                           // <<<<<<< deprecated

Thx

**Comment by overriden-sfdd** [comment]
Instead of `hints.setPossibleFormats(codebars);`,
 you can use `hints.setFormats(ZXing::BarcodeFormatsFromString(codebars));`

and instead of 
`ZXing::Result result(ZXing::DecodeStatus::NoError);`
`result.resultPoints();`,
you can use
`ZXing::Result result(ZXing::DecodeStatus::NoError);`
`ZXing::Position positions = result.position();`

**Comment by Portiella** [comment]
Thanks

**Comment by axxel** [comment]
If your questions are fully answered, please close the issue. Thanks.

(And thanks to @overriden-sfdd for contributing. I believe you are the first person outside the two main developers who solved another users issue! ;))
