### ISSUE TITLE
Improve 1D barcode detection with noisy input

### ISSUE THREAD

**Issue by overriden-sfdd** [nu-book/zxing-cpp#240]
While working on my project, I found one GlobalHistogramBinarizer limitation. I have a sample that has an unusual color scheme. It's clearly readable, high res barcode, but zxing reader fails to detect anything in the image.
![2](https://user-images.githubusercontent.com/47534862/127001590-2ca7a883-8f58-4fc2-a012-5d87136f5f02.jpg)

**Comment by axxel** [comment]
There is no way to detect this image as is with the current code base. I found one relatively simple preprocessing step that fixes this image and that is a gaussian blur (with e.g. 2 pixels radius), which evens out the background pattern just enough.

What would really help in those cases would be to average scanlines after shifting them so that the bars and spaces align vertically. This could be achieved via cross correlation but that is likely pretty expensive in terms of runtime. If the bars are almost vertical (like in this case) it should work by simply averaging vertically as they are. The problem is that this averaging will make other samples fail that work currently.

**Comment by overriden-sfdd** [comment]
That's a nice catch, thank you. I didn't notice this when I tried gaussian blur. According to my tests, gaussian blur doesn't hurt detector's performance on any other image and works perfectly fine with unusual color scheme.
