### ISSUE TITLE
Fail to install the package with VS pakage management

### ISSUE THREAD

**Issue by JoelYYoung** [nu-book/zxing-cpp#241]
While installing the package with VS package management, I get "Could not install package 'xxxxx'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework." 

I have VS2019 16.10 installed, which is the latest version.

**Comment by axxel** [comment]
You are talking about the nuget package? I believe that package contains only ARM binaries and your 'native' comment suggests that this is not what you are looking for. That said, I really have no clue about WinRT/nuget/VS. I'm a linux guy :). Maybe @huycn can provide some insight?

**Comment by huycn** [comment]
The Nuget package provides 4 binaries: x86, x64, arm, and arm64.
I've just tried by creating new C# project using "Blank App (Universal Windows)" template and the package get installed without any issue.

Which kind of project are you trying install the package into? Otherwise, please provide a sample project which we could reproduce the error above?

**Comment by dang-gun** [comment]
I created a ‘blank project’ for C++ and the same error occurred.

**Comment by axxel** [comment]
@dang-gun I don't understand what you are trying to tell us. Can you elaborate?
