### ISSUE TITLE
This QR code is not recognized On the PC

### ISSUE THREAD

**Issue by shaochenguang** [nu-book/zxing-cpp#253]
![sfsdf6](https://user-images.githubusercontent.com/33643378/131627850-901ebde1-34b3-48ee-b5f3-438487e5deb5.png)

**Comment by axxel** [comment]
This is a non-conformant QR Code, due to the rounded corners of the 3 finder patterns. I found a fix for this particular example but it breaks another. I'll have to investigate further.

**Comment by axxel** [comment]
If you really care about this example, you can look at the line https://github.com/nu-book/zxing-cpp/blob/16d13bc663ae05c634651314d5ab900af49e438c/core/src/qrcode/QRDetector.cpp#L73 and replace the string `LocateConcentricPattern` with `LocateConcentricPattern<true>`. That will fix your issue and keep all other samples working as long as you use the new `ReadBarcodes` function (instead of `ReadBarcode`).

Since this change is potentially affecting a lot of other valid samples and this one is sample is technically simply ill-formed, I'd rather not commit that at the moment.
