### ISSUE TITLE
UPC-E detected, where EAN-13 was expected

### ISSUE THREAD

**Issue by uniederer** [nu-book/zxing-cpp#255]
I came across a glitch I don't understand so far:
Whenever I scan the EAN-13 barcode encoded ISBN of a book of mine, it is sometimes (wrongly) decoded as UPC-E code:
![UPC-E instead of EAN-13](https://user-images.githubusercontent.com/2959566/132906853-c752b76a-e439-400f-93fc-0c863b15b0d5.png)

It anyway appears to me, the result is highly dependant of the code's orientation within the image. Not only does the orientation appear to have a huge influence on the barcode discovery in general, it also seems, certain angle cause the decoder to misinterpret what is found.

This behaviour can easily be reproduced with the current reader demo that is provided here:
https://nu-book.github.io/zxing-cpp/demo_reader.html

Decoding appears to work fine if the barcode runs strictly horizontally or vertically.

Any suggestions?

**Comment by axxel** [comment]
It just so happens that the right half of that symbol is also a valid UPC-E symbol if you cut it at just the right place. That happens due to your slight angle. See the following crop where the red line shows the location of the found UPC-E barcode.

![#255-out](https://user-images.githubusercontent.com/1038346/132979765-7b422ebd-36fb-4405-9896-5cd29f9afa40.jpg)

If you have it straight horizontal or vertical, then the thick black bar below the letter `4` prevents that, because there is not enough quite zone for the UPC-E symbol.

You can prevent that from happening by passing `DecodeHints().setFormats(BarcodeFormat::EAN13)` to `ReadBarcode` (see also the `-format` command line parameter of `ZXingReader`).

**Comment by uniederer** [comment]
Thank you for the swift reply. What bad coincidence. 
Unfortunately, I'm supposed to scan both types of codes (that's why I ran into that issue). 

So I assume there is pre-processing that tries to adjust the code's rotation based on the bars detected to make the code horizontal again prior decoding the bars? - Not that I have that thought through. Maybe I'm having a too naive imagination of that step :-)

**Comment by axxel** [comment]
No, there is no such pre-pocessing. If you use the current HEAD, there is another option for you filter out the UPC-E result in this case. My recent Multi-Barcode addition added the `Result::lineCount()` member that tells you how many lines with the same result have been found. You could ignore the result if it has not been found in at least 2 (or more) lines. You might overlook valid symbols this way, though.
