### ISSUE TITLE
Doesn't parse driving license PDF417

### ISSUE THREAD

**Issue by jkflying** [nu-book/zxing-cpp#295]
I have a cropped out barcode from a specimen driving license (attached). The quality is fairly good, but I can't decode it using the ReaderTest. I've tested that this works with other libraries, including via a phone from the screen.

I'm good with C++ and image processing in general, but I've never worked with barcode data before. Assistance in any way (including pointers of how I can debug this myself) would be much appreciated. I tried running it in a debugger but the PDF417 decoder is a bit alien to me and I'm not sure what to look for.

![IMG_CAN_SK_DrivLI_B_barcode_cropped_1](https://user-images.githubusercontent.com/1746276/155702396-078a9d34-ceb9-412e-ab58-92d5b6849db9.jpg)

**Comment by axxel** [comment]
I can confirm that the current implementation fails with a checksum error. I assume the critical issue is a lack of resolution. If the resolution would be at least 50% higher, I'd expect it work. Otherwise it is indeed a good input sample (perfectly straight, non-distorted, complete).

As for the "a bit alien" description: There is nothing to argue here (see also my feelings described in #145) :). That issue also contains quite a few hints as to how the code currently works and could be improved. I started with a 'complete rewrite' in the `isPure` code path in `PDF417Reader.cpp`. If you'd like to look further into this, I suggest we continue the conversion in #145.

**Comment by jkflying** [comment]
Thanks, will continue on #145 .
