### ISSUE TITLE
add release assets without test files

### ISSUE THREAD

**Issue by Arnaudv6** [nu-book/zxing-cpp#312]
Disclaimer: gentoo user here. Thus compiling most stuff from source, yet ecology-conscious. 

To date, uncompressed zxing-cpp release folder is 103.8MiB, with sub-folder "test" being 99.1MiB.
I feel like there could be a release asset "with test files" and a default one without,
so users download and uncompress a 3Mb file instead of 99Mb.

**Comment by axxel** [comment]
I totally understand your intention but what do you mean by "release folder" and "release asset"?

**Comment by Arnaudv6** [comment]
_release assets_ are compressed files for user to download, per release: https://github.com/nu-book/zxing-cpp/releases  
_release folder_ is what you get when you download a zip or tar.gz asset today, say [this](https://github.com/nu-book/zxing-cpp/archive/refs/tags/v1.2.0.tar.gz), and uncompress it.

hope this helps

**Comment by axxel** [comment]
Any progress on this? I intend to make a release soonish, so this would certainly make sense to merge beforehand ;).

**Comment by Arnaudv6** [comment]
Nope : easter holyday with family 🙂

**Comment by Arnaudv6** [comment]
Thanks @axxel. I'm underwater, for long afaict and clearly would not have done this so nice.

**Comment by anthonyryan1** [comment]
I need to object to the solution as it has been implemented here.

I'm a Gentoo contributor trying to re-enable unit tests on this package in Gentoo, and the absence of this test data has now made it impossible for Gentoo contributors & developers to fully test this package before each update is pushed to users.

`git clone` as outlined in #748 is not suitable because we need static tarrballs, not moving targets like git HEAD to provide determinism to the process.

Would it be feasible to split tests/samples into a separate repository, and make it a submodule here instead? That way we can still conditionally grab this data from github as a tarball when unit tests are supposed to be run?

**Comment by Arnaudv6** [comment]
Project has multiple release assets since ages. (I was new to CI and must not have checked back then.)
No asset w/ src but w/o tests tough.
@axxel, if there is no easy fix, please feel free to revert bee813a. And forget about this bug.
Bottom line is @anthonyryan1's testing needs are more important than this (sometimes) extraneous x100 factor on download size.

**Comment by axxel** [comment]
I will not revert that change. I believe those unit tests are not of interest to most people. The only real use I see for external projects (like Linux distributions) is running those tests on platforms that are not supported by gibhub's CI system. This may well be the case for Gentoo.

While separating out the test-images into a new repository is actually something I thought about myself, I don't have the time to spend on this right now. I see two short term options:

 * modify the mentioned git clone approach trivially to checkout a specific release version (instead of HEAD)
 * supplying a manually created tarball that can be added to the release assets page for easy download

**Comment by anthonyryan1** [comment]
Gentoo already has support for grabbing specific tags from git, but I've been told by the developers who are going to be reviewing my request that they won't accept that strategy into the package tree.

So my preference out of the two short term ideas is a manual tarball containing tests. The only downside is that someone here will need to make a new test data tarball on each new release (because I imagine each new release contains a small number of new tests).

It lets us avoid downloading the test data for every user who hasn't opted into test running, but that's mostly going to be developers/contributors/testers for us, rather than end users.

**Comment by axxel** [comment]
Added the tarball for the 2.2.1 release: https://github.com/zxing-cpp/zxing-cpp/releases/download/v2.2.1/test_samples.tar.gz

**Comment by anthonyryan1** [comment]
Much appreciated. Thank you!

I've sent off the changes to the Gentoo tree for review today. End users will still get the benefit of not needing to download the sample data, and anyone wanting to run tests will automatically fetch that tarball and run the full test suite.

It should give us much stronger assurance on future releases that there's no unexpected regressions.

**Comment by axxel** [comment]
Awesome, thanks for your help in increasing the reach of this project (and my work on it ;)).
