### ISSUE TITLE
error: could not find git for clone of stb-populate

### ISSUE THREAD

**Issue by shuimuquan** [nu-book/zxing-cpp#321]
I compiled the code with CMake, but the following error occurred.  Environment is Win10, VS2019, who knows what is the reason?  How to solve it?  

Looking for C++ include pthread.h
Looking for C++ include pthread.h - not found
Found Threads: TRUE  
Performing Test COMPILER_NEEDS_FLOAT_STORE
Performing Test COMPILER_NEEDS_FLOAT_STORE - Failed
Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
CMake Error at D:/cmake3.21.0/share/cmake-3.21/Modules/ExternalProject.cmake:2650 (message):
  error: could not find git for clone of stb-populate
Call Stack (most recent call first):
  D:/cmake3.21.0/share/cmake-3.21/Modules/ExternalProject.cmake:3700 (_ep_add_download_command)
  CMakeLists.txt:22 (ExternalProject_Add)

**Comment by axxel** [comment]
The problem is no the pthread.h but the missing `git` command line utility. If you don't want to install `git`, you might be able to build the library only (not the test or example or wrapper binaries) if you disable the respective `BUILD_`-options (e.g. with `cmake-gui`). But this is untested. I suggest you install `git`, though.
