### ISSUE TITLE
Unable to decode CODE39 

### ISSUE THREAD

**Issue by glitchyordis** [nu-book/zxing-cpp#330]
![20220119_162017-0-_tM8195A](https://user-images.githubusercontent.com/99534415/167051160-34fc1449-3278-4a47-8b94-8775666663aa.jpg)

Hi, zxingcpp.read_barcodes() has been able to decode multiple barcodes in a figure. However, the code didn't work well for this figure. Kindly assist me with this. Thank you.

code (with python wrapper v1.3.0):
import zxingcpp
import numpy as np
import cv2

img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
[results.text for results in zxingcpp.read_barcodes(img_gray)]

Expected result: 2 barcodes decoded

Actual result: ['M8195-69502']

**Comment by axxel** [comment]
Your code is correct. The problem is the detection of the lower barcode. And that is caused by a limitation of the `GlobalHistogramBinarizer` that fails to properly distinguish between black and white here due to the greyish background that interferes. It is basically the same issue as in #82. If you crop away the metallic background it works. I hope to sometime be able to overcome this limitation.

**Comment by glitchyordis** [comment]
> Your code is correct. The problem is the detection of the lower barcode. And that is caused by a limitation of the `GlobalHistogramBinarizer` that fails to properly distinguish between black and white here due to the greyish background that interferes. It is basically the same issue as in #82. If you crop away the metallic background it works. I hope to sometime be able to overcome this limitation.

Thank you for the help. Your suggestion worked.
