### ISSUE TITLE
Consuming zxing-cpp/core via CMake forces consumer to c++11

### ISSUE THREAD

**Issue by ryantrem** [nu-book/zxing-cpp#355]
I have an existing C++ project using CMake and I am pulling in zxing-cpp/core. As soon as I do this (before I even try to use zxing-cpp in my code), my project no longer compiles because it says a bunch of c++ stuff I use doesn't exist in C++11. Basically consuming zxing-cpp/core causes my project to switch from c++17 to c++11. [zxing-cpp/core/CMakeLists.txt](https://github.com/nu-book/zxing-cpp/blob/master/core/CMakeLists.txt#L468) has this:
```
# the lib needs a c++-17 compiler but can be used with a c++-11 compiler (see examples)
target_compile_features(ZXing PRIVATE cxx_std_17 INTERFACE cxx_std_11)
```
If I change it to:
```
target_compile_features(ZXing PRIVATE cxx_std_17 INTERFACE)
```
Then my project compiles correctly. Is this part of the CMakeLists.txt wrong? Is this saying a consuming project *must* use C++11?

**Comment by axxel** [comment]
> Is this part of the CMakeLists.txt wrong?

Good question. My understanding was that this line makes sure the consuming project uses _at least_ c++11. That said, since yesterday, this is obsolete anyway. We now need c++17 in the public API as well (forgot about this line... will either remove it or modify it).

> Is this saying a consuming project _must_ use C++11?

That was never the intention. It actually feels like a cmake bug to me. Anyway, this line will be gone or changed.

**Comment by axxel** [comment]
The cmake doc says:
```
target_compile_features(mylib PUBLIC cxx_std_11)

In this example, CMake will ensure the compiler is invoked in a mode of at-least C++ 11 (or C++ 14, C++ 17, ...)
```

That is exactly how I assumed it to be interpreted. No idea what went wrong in your setup.
