### ISSUE TITLE
Release notes mention a breaking change in the Python interface as a "minor change"

### ISSUE THREAD

**Issue by OvervCW** [nu-book/zxing-cpp#368]
Release [v1.4.0](https://github.com/nu-book/zxing-cpp/releases/tag/v1.4.0) contains a breaking change in the Python interface:

>python `read_barcode` returns `None` if no symbol was found

This is listed as a "minor change", but I think it should be listed as one of the main changes since it's something people need to be aware of before updating.

**Comment by axxel** [comment]
I see your point. Thanks for pointing it out. I did not consider it as a 'real' breaking change because the type of the object did not change and could always have been `None`. Anyway, making it more obvious that something changed can't hurt.

Note: I consider the function `read_barcodes` as the main/standard API as it is simply superior. I would actually consider deprecating `read_barcode` at some point in time. Why do you use it?

**Comment by axxel** [comment]
Release notes are updated. Please close if you feel your issue has been addressed.

**Comment by OvervCW** [comment]
In our use case we know that there will only be a single barcode in the image, so `read_barcode` simply sounded like a better fit.

I noticed that `read_barcode` sets a hint for the maximum number of symbols whereas `read_barcodes` doesn't have that option. Does this have an effect on performance?

**Comment by axxel** [comment]
You are correct. In that case, `read_barcode` is the better fit and has a performance advantage as the search stops as soon as the first symbol is found. `read_barcode` is simply `read_barcodes` with `setMaxNumberOfSymbols(1)`.
