### ISSUE TITLE
Code 39 is not being detected

### ISSUE THREAD

**Issue by mbaros100** [nu-book/zxing-cpp#371]
I have an image with multiple barcodes where code39 is being correctly recognized. But whenever i trim that barcode and try to recognize it separately, it does not work (i even tried padding the image).
![a](https://user-images.githubusercontent.com/8537079/183250065-34740ff3-76e8-4cf5-aae4-73e34c6caf7e.jpg)
![b](https://user-images.githubusercontent.com/8537079/183250067-6d50eb9a-3d62-499f-a8a6-4b3bcbd09410.jpg)

**Comment by axxel** [comment]
Did your problem disappear?

**Comment by oehhar** [comment]
Vahagn,

thank you for the comment. A complete Code39 code has left and right white Zones of 10 times the small bar. This is not respected if you trim it. In consequence, it should not be readable. If it is read, it is an error.
An unreadable example is your code sample b.

Take care,
Harald

**Comment by axxel** [comment]
Harald's comment about the quiet zones needs one addition: a minimum quiet zone of x pixels means there may not be any black pixels closer than x to the symbol but the image border is not considered a black pixel, i.e. symbols can be cropped to 0 pixels white-space around them and still be recognized. Your second sample does not work because you cropped away the rightmost black bar.
