### ISSUE TITLE
Rectangular DataMatrix not decetced without padding/quiet zone

### ISSUE THREAD

**Issue by mbaros100** [nu-book/zxing-cpp#378]
![g](https://user-images.githubusercontent.com/8537079/183855116-2f2962f3-ac0c-402f-bf9c-7cd4a7f9672e.jpg)

The following barcode is not recognized by the library.
However, some online tools are able to recognize (https://products.aspose.app/barcode/recognize   or   https://online-barcode-reader.inliteresearch.com/)

When i pad the image by 1 white pixel from all sides it is being recognized
![g2](https://user-images.githubusercontent.com/8537079/183855548-2267c819-3925-428e-afb5-abe15fa7c89f.jpg)

So this is kind of a missed corner case when barcode exactly fits in the pixel area

**Comment by axxel** [comment]
This is what we call a 'pure' barcode. If you set `DecodeHints::setIsPure(true)` it gets detected (and is faster, too). See also `-ispure` command line argument of `ZXingReader`. Technically, this image does not contain a valid DataMatrix symbol because it is required to be surrounded by at least 1 module of white. Typically people know in advance whether or not the input is 'pure'. If you don't, you can simply try both options.

**Comment by gitlost** [comment]
A simple workaround for this issue, which is annoying to encounter, is to have `DataMatrix::Detect()` call `DetectPure()` if `DetectNew()` fails and the `tryHarder` flag is set (https://github.com/gitlost/zxing-cpp/blob/9d5228238841a9f04b5a725de611b0dcdd113af8/core/src/datamatrix/DMDetector.cpp#L937), which might be worth considering.

**Comment by axxel** [comment]
@gitlost you are absolutely right. the performance penalty for this change is negligible. done.
