### ISSUE TITLE
Possible wasm support

### ISSUE THREAD

**Issue by vanthiyathevan** [nu-book/zxing-cpp#40]
It has been done for the other cpp port
https://github.com/H-Plus-Time/web-zxing

**Comment by huycn** [comment]
That is interesting, I didn't know such thing exist.
Thanks for your suggestion, I will definitively look into it when I have a chance.

**Comment by Naahuel** [comment]
Thank you for this! I needed PDF417 support in WebAssembly and you saved me.

I came from using ZBar in WebAssembly and the .wasm output file was only about 50K but with your build I get a 1.3Mb file which is considerably larger. I think it's mostly because ZBar allows me to disable different symbols and only enable those I'm interested in. Is that possible to do? Thanks

**Comment by huycn** [comment]
There is a build option in `CMakeFiles.txt` to disable either all encoders or all decoders. If you don't need to generate images, just disable encoders will reduce file size about 0.5MB.

To disable individual decoders, you can have a look at `core/src/MultiFormatReader.cpp` and comment out symbols you don't need. You can leave them in project without problem. As this is the only place where they are specifically referenced, the linker will do the job of removing unused code.

**Comment by Naahuel** [comment]
Yes, I'm already disabling encoders. I'll take a look at disabling symbols I don't need from that file. Thanks!

**Comment by Naahuel** [comment]
@huycn That worked. It's now on ~800Kb which is more acceptable. It would be great to be able to disable specific encoders or decoders as a configure parameter but this works for now :)

Thanks!

**Comment by huycn** [comment]
Hum... 800Kb is when I disabled encoders with -DENABLE_ENCODERS=0 but leave all decoders active. When I disable all symbols except PDF417, I got 400Kb. I believe there still something not removed properly since 400Kb is still a lot, considering PDF417 doesn't need TextDecoder where unicode data mapping takes a good amount. I'll  look further into this later. But now, 800Kb what you get is something unexpected. Are you sure you compiled with `-DCMAKE_BUILD_TYPE=Release`?

Also, you may want to try to edit `wrappers/wasm/CMakeLists.txt` and add `-O3` at line `set (CMAKE_CXX_FLAGS ...`. I remember I played a little bit with my emscripten installation to make -O3 instead of -O2 as default flag for release.

There is also RTTI and exceptions we can disable to reduce further file size, but some reason I ignore, I got compilation error when I try to disable RTTI with -fno-rtti
