### ISSUE TITLE
Qt wrapper

### ISSUE THREAD

**Issue by swex** [nu-book/zxing-cpp#75]
Hi there!
Thank you for great project!
I've made wrapper for Qt based applications: https://github.com/swex/QZXingNu
If somebody interested feel free to use it and improve.

**Comment by axxel** [comment]
+1 :-)

May I ask you the following questions (out of curiosity)?:
 * I guess you are aware of the "officially referenced" Qt-Wrapper based on the original/old c++ port (https://github.com/ftylitak/qzxing)?
 * How does your wrapper compare theirs?
 * What made you invest in this work instead of using their existing one?
 * Have you approached them whether they would be interested in joining forces?

**Comment by swex** [comment]
1. Yes I know about qzxing, I've made my own, based on your zxing rewrite when I failed to get qzxing to work it was about a year time ago [see](https://github.com/ftylitak/qzxing/issues/86). And about the same time I discovered your rewrite and implemented new wrapper. btw upstream fix merged 7 days ago.
2. No I don't think so. I'd be happy to Qt community to have one barcode encode/decode library to rule them all. I'm just not happy with amount of legacy code in original zxing
3. See 1
4. Kinda, https://github.com/ftylitak/qzxing/issues/81#issuecomment-504464955 let me make it here: @ftylitak please replace old zxing with one from this repo. I've already made it, feel free to take necessary code parts to your repo

**Comment by ftylitak** [comment]
Hello @swex  and @axxel 

I too believe that there should be a unified solution with the C++ part of ZXing, no argue. 

Though I have got some concerns on which I am open for discussion. 

There are a couple of implementations of C++ ZXing. To name a few:
* [nu-book/zxing-cpp](https://github.com/nu-book/zxing-cpp)
* [glassechidna/zxing-cpp](https://github.com/glassechidna/zxing-cpp)
* [ftylitak/qzxing](https://github.com/ftylitak/qzxing) (this is added taking into consideration the ZXing C++ part leaving aside the Qt specific parts)

To my understanding, each of the implementations/approaches started with a specific goal from the creators which I appreciate because they are all valid. For example, it is very nice to see the fresh and state of the art implementation of **nu-book/zxing-cpp** with C++14.  Meanwhile, it is very acceptable to see **glassechidna/zxing-cpp** being a direct continuation of ZXing C++. This was the goal of QZXing as well, even though it remained more targeted to Qt. 

One important aspect for me is also the starting date of each project. That is because the era that a project begins somehow defines its purpose and target path. For example, **ftylitak/qzxing** started on 2011 as a Qt wrapper of the ZXing C++ project which was alive back then. After the last release of ZXing C++ port (November 2013), I was not in position to further develop ZXing port though I could maintain the wrapper. A year and a half after, **glassechidna/zxing-cpp** was created. This takes us to the starting of 2015. Especially till then, C++98 was still very much in use so we all continued the code base as it was. **nu-book/zxing-cpp** started around April 2016, if I am not mistaken.

Why i do the historical overview you might wonder. Once a project is somehow stabilized after some years of existence, it is not that easy to make radical changes. Call it because of possible code incompatibility? Call it because of lack of time? Call it because of fear to the "unknown"? Everything adds up. 

Now, I will talk for QZXing. I would very much like to use the ZXing C++ part from other sources though my time is very limited and I do not know when will this happen (I keep this project as a hobby). Moreover, I would not want for the time being to use **nu-book/zxing-cpp**, even though it is great, solely because there are quite a lot of projects that use QZXing that do not yet target platforms that support C++14. This would mean a break in the backward compatibility which is not desired for the moment. (into some extend, the above are also mentioned in a post of mine here: https://github.com/ftylitak/qzxing/issues/1#issuecomment-245842264)

@swex it is good that you made the Qt wrapper for **nu-book/zxing-cpp**. It is good to see such initiatives. Though, I hope you understand my differentiation.

I need to express again that all the above are just personal opinions/views. In case I am mistaken at any part feel free to correct me. Nevertheless, I remain open for discussion. 

Best regards
@ftylitak

**Comment by axxel** [comment]
Thanks @ftylitak for chiming in on the matter and also explaining a bit of the history of your work. I have a question: if your wrapper dates back to the original/official c++ port, what did you do after it got 'abandoned'? And when glassechidna's fork started, did you base your wrapper on that code base or does it still 'contain' the original code (with a few fixes from your side?)?

I'd like to comment on two of the points you mentioned, that hold you back from jumping on a new c++14 based implementation:
 * "develpment time/resources": obviously totally valid in general and I have no idea how intertwined your wrapper is with the internals of the original port or how much more your wrapper provides compared to what @swex has done.
 * "c++98 support": I'm admittedly a fan of the 'living at head' approach as much as practically doable. I guess I'm lucky that I run my own company and am not holt back by corporate/legacy structures. That said, I really don't get why any development team would not have gotten around and installed themselfs a c++11 compiler (in 2019), especially those that rely on open source projects like yours. And isn't Qt itself depending on c++11 nowadays? And if you've gotten that far, then c++14 should not be an obstacle either.

Anyway, this fork is mostly the work of @huycn and like you, I don't have much time to spent on it either. But if you have specific issues or questions in case you want to start looking into the possibility of porting your wrapper, I'd be happy to help. What you should get in return is all the improvements and bug fixes that went into the java upstream since the deprecation of the c++ port, my improved DataMatrix detector and quite a few performance improvements and memory leak fixes.

**Comment by ftylitak** [comment]
To comment at the two bullets for yours, 
* I would guess that there is little to non interwining between the wrapper and the actual ZXing code used. Thus it would probably be easy to use other ZXing implementations. 
* I admit that indeed at some point every one of us needs to be become up-to-date. After a lot of thought regarding the approach on the C++ version to be used, I came to the decision that from my side I will follow the C++ versions used by the LTS versions of Qt. That is because I target Qt so I need to follow its ecosystem.  Thus, from Qt 5.9 and on the official C++ version is C++11 so I will gradually move on to it.  This would answer to you why not C++14. Though, I wonder (without having seen your source code yet), is your implementation that far from pure C++11? 

Through the coming couple of months  I will try to find some time to decide the next moves and I will let you know. Regardless my decision, thank you very much for your intention to help.

**Comment by axxel** [comment]
@ftylitak quick question: any updates on your situation/decision regarding requiring your user base to update their tool chain? Another year has passed and @huycn and I have decided that we'd like to move to c++17 (and that was almost two years ago already ;)).

**Comment by ftylitak** [comment]
Greetings, 

having as a trigger, @axxel 's comment in issue https://github.com/ftylitak/qzxing/issues/151, it would be good of me to make a last comment. 

Indeed [nu-book/zxing-cpp](https://github.com/nu-book/zxing-cpp) does a great job and congrats to all the contributors. 

My decision on not to switch the backend from the current implementation to [nu-book/zxing-cpp](https://github.com/nu-book/zxing-cpp) is based on 2 factors: 

1. the most important reason is that there are many companies that are still using Qt 5.2-5.6 due to licensing issues. This includes Sailfish OS for example. My preference is to be able to use this library as freely as possible. 
2. also here comes my lack of time. A wrapper could be made in QZXing to provide the **option** of using [nu-book/zxing-cpp](https://github.com/nu-book/zxing-cpp) backend. Though, I do not have plans of implementing such a wrapper due to very free limited. The thankful part of opensource projects is that any contributor willing to implement such a thing will be very welcomed. 

Keep up the good work :)

**Comment by axxel** [comment]
@ftylitak The name qzxing came up again [recently](https://github.com/zxing-cpp/zxing-cpp/discussions/716#discussioncomment-8388507) which reminded me of this old conversion we had. 2,5 years gone by already... Realizing that the last commit to your repository was also 2 years ago, is it fair to assume that you abandoned the project?
